### PR TITLE
Fix zuul playbook

### PR DESCRIPTION
**Pull request by oshogbo**
I think this is the missing part to fix zuulu.
It would be good to have a ci/cd attached to this project.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)

### CODE REVIEW

**Review by piotrpalcz — APPROVED** [review]

**Review by piotrpalcz — APPROVED** [review]

**Comment by oshogbo** [comment]
@piotrpalcz Hi, you have to accept it in reviewable, otherwise, the merge is still blocked.

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`.zuul.d/jobs.yaml` line 58 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9#-Ne2Gkxw2q42mxb3C7O2:-Ne2Gkxw2q42mxb3C7O3:ba9jsxu) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/9aa1446e0728272616951211c17037c5424470ea/.zuul.d/jobs.yaml#L58)):*
> ```YAML
> 
> - project:
>     name: woju/gramine-scaffolding
> ```

This ^ line is the reason why zuul 500's the webhook. The project is now `intel/ScaffoldingForGramine`.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`.zuul.d/jobs.yaml` line 58 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9#-Ne2Gkxw2q42mxb3C7O2:-Ne2oYro2bfUt0vGLwib:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/9aa1446e0728272616951211c17037c5424470ea/.zuul.d/jobs.yaml#L58)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This ^ line is the reason why zuul 500's the webhook. The project is now `intel/ScaffoldingForGramine`.
</blockquote></details>

Done.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`.zuul.d/jobs.yaml` line 67 at r2](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9#-Ne2ttkmA_Po4qAiuDgF:-Ne2ttkmA_Po4qAiuDgG:bm9kbxd) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5645ff00bb8aca46d14bca0ce1379c52ed669bb7/.zuul.d/jobs.yaml#L67)):*
> ```YAML
>         - build-docs
>         - example-python
>         - example-flask
> ```

This needs to match `- job: name:`



_Suggestion:_
```YAML
        - test-python
        - test-flask
```

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`.zuul.d/jobs.yaml` line 67 at r2](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9#-Ne2ttkmA_Po4qAiuDgF:-Ne3gXCXCQ1SRelKFyAe:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5645ff00bb8aca46d14bca0ce1379c52ed669bb7/.zuul.d/jobs.yaml#L67)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

This needs to match `- job: name:`
</blockquote></details>

Done.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
