### PR TITLE
Add github templates

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/26)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/5ba92c85fe9640bd850966155818ff9b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/87604693aed045e7a6e21965a1ce228e) SUCCESS in 42s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a5ceeca2375948eb864ee9dd8896ae8d) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/71f8ed77f9e1440a9877cae20dc38c50) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/ef1b3a02aa6048fbb51df23e6b2bf42b) SUCCESS in 1m 11s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/f53b647849d24c528512024e79b4b74b) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/80e19cd456e2444ab32b125aa3914c88) SUCCESS in 4m 41s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/fd44e9cf0b634998b0b6a1013db1a0ee) SUCCESS in 6m 22s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/710df408847149e6acdd60411256b217) SUCCESS in 5m 16s

**Review by woju — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/5ad51f27cd174b418dc95af883af1c07

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/478a22e63b7d48bab7057bccd009c4ab) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a5a23f54024f4d88b28ca665167947fb) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/20867056e5974095a5743fb20151ad30) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/b0d606ec67d64415a49ad6344157115c) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/a1e0faddc6e64a538e6613fa305980a8) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/40721dac8a87461f8ca4a8c38f81ab66) SUCCESS in 2m 37s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/766ccdcecf8547a2901b36c80ef53ed0) SUCCESS in 3m 05s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/715eda93a8b94ea4af419b01ccd35f1e) SUCCESS in 3m 18s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/89693f36dc9b455182cb017f3ebed9be) SUCCESS in 4m 25s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/98cc35f1885b4856b70ae0fa116fe5c8) SUCCESS in 6m 38s

**Review by woju — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
