### PR TITLE
Customisation (templates, Dockerfile)

### PR DESCRIPTION
**Pull request by woju**
Add two (one and a half) ways to customise the image:
- external templates can be provided, which take precedence over builtin templates
- one of those templates is `Dockerfile`, and it allows for adding extra docker build steps in `{% block local %}`

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/34)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/8f8925c875ed4cd7af4131434ca539fc

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/7ce654b5cdb14401af18fc1ce37b0149) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/bb7666817e8546d3ac13c8be2d3e9223) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/616c6e0e64184b4797a00cfc4db8ac56) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/50f79a8486594d4f8235ab1b5264ae59) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/ebc3f0ecc99b493ab2677c7fccf4fce5) SUCCESS in 38s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c1e8000773814fa1adb82756f19793d5) **FAILURE** in 1m 21s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/e4001c8da44f4f98a19ab6adfe636f1e) **FAILURE** in 1m 18s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/b62a44dcbb954c4fb73d56457f8a5700) **FAILURE** in 1m 20s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/7ee138fb53cd4b008b4488200bce208b) **FAILURE** in 1m 17s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/4ac15b6d49d345c7909c71d95ef5741c) **FAILURE** in 1m 47s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/b1bbf5da40d24ab58842257438748674) **FAILURE** in 1m 19s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/eaa824d0a2d74d3d844fd7900422aa9e) **FAILURE** in 1m 24s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/a4e0e3a0ecd141f3984ca36bae224d7f) **FAILURE** in 1m 19s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/d343039058bc42ea9471859579694242

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8736c4c1d1474c708d0bce521e1aeb8b) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/4fc434ebbcd741fba7f6fe804835d0d7) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d315828761984f4ca75be949b15d518e) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/387a09cc41224ff38500dcc21950563c) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/39576a0cfe6d436ab4206a2dfd737569) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/bd23c011cd4448e88f514ee206e4da05) SUCCESS in 2m 54s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/94f6367d56684992baa108d5e63e7ba3) **FAILURE** in 3m 07s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/fb410061fdf8450cb1860b93ccbe800e) SUCCESS in 3m 15s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/efa505a075b448799224ad51a6bfd3bd) **FAILURE** in 5m 44s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/aad0758e5ba7410fb6af8027acc52bee) **FAILURE** in 5m 31s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/c56f47480e1240b4b172f0c4706529e6) SUCCESS in 4m 48s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/6d5c8384065e41f38d20d15f60520454) SUCCESS in 8m 59s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/412f17909b8b4d81afe4a22b97f41159) **FAILURE** in 6m 03s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/e658f9c95ded438685e6d87d36795d80

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/bc8c077c0fd34ea5a3c5e127ac453a89) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/b3ac28adaa5645b786aa24ea19b9a4be) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/88aa72ed88a24e16a24ff7f9b62bbe93) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/b4fa110bdaf5412f8313c92f7a6525f4) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/43ae8faebfa74b40a0b5f0d642442da0) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c38d9a4c77184bc794cf9d926d40651b) SUCCESS in 3m 08s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6cb8d4ca2f8748bd9e09f31881d54ff8) **FAILURE** in 4m 23s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e48f05217bc84eecbbc5ad045df202dc) SUCCESS in 3m 33s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/845ab4e8760c4fc0acb94daf7628903b) **FAILURE** in 6m 06s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/c70aca6aa27149feaefe565245d5486c) **FAILURE** in 8m 41s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/89aa42c3d8fa49b19a5d98a458c1161d) SUCCESS in 7m 56s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/285c8b6ef5714356b26dfecf592f097c) SUCCESS in 10m 43s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/d15ec6f2f3c54796ab6ed9c53e1d908d) SUCCESS in 10m 29s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/e8307b88e0b94069bd7103658bb86b41

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/c7b8ad68150f460f8e90725e3520f02e) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/90d718b6e0bd41c9b4e1521b1829018a) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/7c8b4baa872541789fc040b07fe3fbc4) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/63c89fc204f44ae28d7cd5edba603d22) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/796188c6499d418f8d8770492777ae9b) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/4e84cc9405b84333aa77010c8bb9dfd4) SUCCESS in 3m 08s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c747b635313c4e6dbc3a796534353721) **FAILURE** in 3m 14s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/bafa600dfb394c3b9dbaafa524b98f4b) SUCCESS in 3m 34s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/4152acfc60884b0fab6f6ab32e161b75) **FAILURE** in 6m 53s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/c2071943653d401db84cf3462d447045) **FAILURE** in 5m 44s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/4e87eeca05914e35b48b7bb061ecf25e) SUCCESS in 7m 47s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d57a1482954146a98d0a226464e1c17b) SUCCESS in 12m 44s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/8d45b99b132944d7adce85e7c6747655) SUCCESS in 9m 58s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/4b725d771a544015b4877c94c9718ae3

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/05a31ba77e0f43c9bdd45362ee80cb7f) SUCCESS in 42s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/e6de4bc9525940478d421d8b165fe05e) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a72bd9c4a2fa41c995fd7798cb15b388) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/ae318d63b1224505a00a8c8e34e17c6c) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/635fed5d45294dd9a8f633cdfe10abe7) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0f36a6f7d2cc4ba4aa76e8f4bfc1cba4) SUCCESS in 3m 00s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/5277a11e18ad413383744c0d993f04a7) SUCCESS in 3m 06s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/6c313d18334745af8e5f40d4cfe883e9) SUCCESS in 3m 23s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/9979ebb2144a4a59b5408efa2974dc28) SUCCESS in 6m 19s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/0a78a263f2f143c4bc96c22a9c444c32) SUCCESS in 6m 46s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/1c2cb5d0ed09404c86423ef7be06bdeb) SUCCESS in 6m 37s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/fc436fae1e964eb1af0ca4b58c612679) **FAILURE** in 4m 40s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1e1333cb8ba041ceada387c88321f002) **FAILURE** in 3m 45s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/60c8337a40d04c6ebf9170cf30dccc6b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ad94ec39b7684db59c85c83f36d2f74d) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/949c006616054ae9a0e17d668df79959) SUCCESS in 52s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/56333bec36154cb1a365c902b4a14062) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0b8ed03f35344747be96a2f151f30fd6) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/13867f6d3998457299b23cdaebd9cf58) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/8afc62460a7649d7a40765007e538b03) SUCCESS in 5m 11s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/ea1bb929f0ee45fda2e1bc95a1a18495) SUCCESS in 5m 37s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/084adc46d6b2494b803f72417237ffd4) SUCCESS in 5m 56s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/f1a0a88e1a9c40eab158744942f1358c) SUCCESS in 7m 50s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/21209e9696ad4aac9ddce60a0fc686dd) SUCCESS in 8m 48s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/8f4a312b62bf4027bb074b5a9b0f8499) SUCCESS in 7m 26s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/53a05c1b2f3f4448bbe657db9fc998fd) SUCCESS in 11m 16s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/85c914ecf3984438b8608c145e38a14e) SUCCESS in 10m 56s

**Review by oshogbo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/34)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`graminescaffolding/builder.py` line 73 at r2](https://reviewable.io/reviews/intel/ScaffoldingForGramine/34#-NniZGiH8j6vFUZWtgMP:-NniZGiI8Vbp5DQYfvdS:b-y4ptek) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/ab7b58e33ad339dd5a1c1ba074556370946647e6/graminescaffolding/builder.py#L73)):*
> ```Python
> def filter_shquote(s):
>     return shlex.quote(os.fspath(s))
> _templates.filters['shquote'] = filter_shquote
> ```

New line by się chyba przydał. Albo może lambda?

```
lambda s: shlex.quote(os.fspath(s))
```

Non blocking.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/34)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 73 at r2](https://reviewable.io/reviews/intel/ScaffoldingForGramine/34#-NniZGiH8j6vFUZWtgMP:-Nns7Vz9DG_-c4Enux-O:b-1j3z04) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/ab7b58e33ad339dd5a1c1ba074556370946647e6/graminescaffolding/builder.py#L73)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

New line by się chyba przydał. Albo może lambda?

```
lambda s: shlex.quote(os.fspath(s))
```

Non blocking.
</blockquote></details>

In Python, if you define function or class and immediately add it to some collection, there usually is no newline between last statement and the statement that add to the dict.

I don't want to do `lambda`s, because they don't have names, and if traceback goes through them, it will only say `<lambda>` and line number, which would be OK here, but is very problematic when you have two lambdas on the same line. I don't want to introduce lambdas in this codebase.

**Pull request merged**
