### PR TITLE
Use unix domain sockets instead of ports

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build canceled.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b79aaa5662ad47fe91899420bcabf005

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/2e48dfc770614e9ab740c27be5bd23d9) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/faa7e9f96f3a4064808d4de5d2b3d024) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/85968fb0915d42918b333f9f5180ce8c) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/ec89ae23909a46d0bd269b96d1894768) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/efd672a6c04548b68f230f00cbe59c03) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/3f10fc4863eb41489780e873e4327abc) SUCCESS in 3m 04s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/30ece6a0f7b647a7b43976928be6b587) SUCCESS in 3m 25s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/67e930b5fdd047ca8af9b9e13d187330) SUCCESS in 4m 21s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/28c674a2f6904a88b2ecbe2cf0e66bde) **FAILURE** in 7m 14s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/0a3d521e8bfe44c597727f10ab63d492) **FAILURE** in 7m 15s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/a0256464b58f4cdcac4b48aad47169e0) SUCCESS in 6m 19s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/0c34a2fb45f942ecb0352e46e324b07b) SUCCESS in 14m 00s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/9241e2072f3a4fc48ec4fdc7799aee06) SUCCESS in 11m 02s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/959a17abe75a46588cab9c92da1924f6

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ae63a8acc2be4992a709d1ebda33a94f) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/399cf85de19b40fe85c53522e0842e9f) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a8e45c98042b4044b32435adb28a999e) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/5a5dbf6a3dee4dca828867ed7a23dd3e) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8d7410885a12414fa10c1a8d658f5b24) SUCCESS in 40s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/479d24898cfb4319a4681021acf79efd) SUCCESS in 3m 03s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f62232ec743f4e9192667de940172d39) SUCCESS in 4m 40s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/2f832cd1206f4a42b283f7b99e561065) SUCCESS in 3m 40s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/c2e12d12c8b54dd7a7f8bfc79b6e1589) SUCCESS in 6m 40s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/889d2930af87476193cecef45c46a716) SUCCESS in 8m 04s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/cb67dbcdbcf24d999978fad4c5e3e5cd) SUCCESS in 6m 27s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/0ae7888389c2437ea320e86562d2bbc1) SUCCESS in 12m 37s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/46f83e3a9e4a40c19e8ee36cc235d76e) SUCCESS in 10m 50s

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`Documentation/manpages/scag-setup.rst` line 75 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42#-NoRuPnt8WK8vlzP4nnd:-NoRuPnuCoEkjrgfbMeh:b5bhk4) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/85e1a159983f724a250fc6d5f6263949cee77ea9/Documentation/manpages/scag-setup.rst#L75)):*
> ```reStructuredText
>     Express.js application main script.
> 
> .. option:: --expressjs_internal_unix_domain_socket
> ```

Can we just remove this option and hardcode the socket path? I think it's never needed to adjust it, and if you put it in mounted fs, it's would be bad or at least confusing. We should have some well-known socket like `/tmp/http.socket` (like in default `nginx.conf` template block) or `/http.socket` (I think every framework, incl. uwsgi, puts it in `/` — then we should also put it in default `nginx.conf`).

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`Documentation/manpages/scag-setup.rst` line 75 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42#-NoRuPnt8WK8vlzP4nnd:-NoRwGrDDSRlAp2EzU4k:b-15y0de) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/85e1a159983f724a250fc6d5f6263949cee77ea9/Documentation/manpages/scag-setup.rst#L75)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can we just remove this option and hardcode the socket path? I think it's never needed to adjust it, and if you put it in mounted fs, it's would be bad or at least confusing. We should have some well-known socket like `/tmp/http.socket` (like in default `nginx.conf` template block) or `/http.socket` (I think every framework, incl. uwsgi, puts it in `/` — then we should also put it in default `nginx.conf`).
</blockquote></details>

We can't forget that the application that is put in the gramine also can be used on development machines and so on.

So we have to provide either the page with "requirements" for the given application or the option to configure the communication channel.

On the other hand, even when we provide an option, we still probably should document how nginx integrates with the user's applications.

So I don't have a strong opinion here.

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`Documentation/manpages/scag-setup.rst` line 75 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42#-NoRuPnt8WK8vlzP4nnd:-NoS9iGzC21ewnCg6Btm:b2myd73) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/85e1a159983f724a250fc6d5f6263949cee77ea9/Documentation/manpages/scag-setup.rst#L75)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

We can't forget that the application that is put in the gramine also can be used on development machines and so on.

So we have to provide either the page with "requirements" for the given application or the option to configure the communication channel.

On the other hand, even when we provide an option, we still probably should document how nginx integrates with the user's applications.

So I don't have a strong opinion here.
</blockquote></details>

Devel mode can have it's own logic to decide how nodejs will be listening and supply different values to `listen()`. For now, I'd hardcode this. We can revisit this in the future.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/9926d4aca0524898a5ba9b95c0655ff0

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/58cfdd034e254359b8ada34f905b5901) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/9cc1ea1df03f4a5187458e60b97e1677) SUCCESS in 52s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b1d48fc3744a4f54a9f123f46bd35969) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/d6dee8ee03394ef290543ae1d8546090) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/90777688067a4370a65c9cd3baabf2ec) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/3a4757f000064fb3bb026ad0117440d9) SUCCESS in 3m 05s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/d01743f3445c4429b25ab9c09a329e78) SUCCESS in 4m 28s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/7108b1138cc5482db7a6029499b4bbbb) SUCCESS in 4m 26s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/41ef6025c77c4a88ac606e69a6c01ea3) **FAILURE** in 1m 01s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/def2212ba41045978325358010aacf6e) **FAILURE** in 58s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/5e10138482634e959fc2f6e4905f4f7a) SUCCESS in 5m 19s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/f4d135cf675b41d29b7844c8b507ac58) SUCCESS in 14m 36s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/7a7138f957254fa68f61862d3030d608) **FAILURE** in 11m 09s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/3b28c14b51744fba841c6426b030af16

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/1daa4eaec77245be84eec5be5bf06a9b) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f5f5097ed4464c2ab09a10ec96cf4817) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/19ee010fd88a47308899bc66130ce44b) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/196b19f175ce4f96be2129c2118871bc) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/22edbdbc17604bdd9126d0ef7a985719) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/92ebb982cd5944dc9777897263387de4) SUCCESS in 3m 42s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c1b723cf3bf042fe9afb5e2d4887aef2) **FAILURE** in 5m 24s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/b663723f83f04012ae8939b549e25f8b) **FAILURE** in 6m 03s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/6ba0537663564f329a7947b4f8b40f9a) **FAILURE** in 8m 04s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/c19bbc6095784899880c7d51588d91b0) **FAILURE** in 13m 14s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/5a4f655992f448dabfc50dac8f08dccb) SUCCESS in 8m 45s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/979a65d2c0994693a2dfbd870b728a80) SUCCESS in 20m 06s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/45fd7ab1d7014ccab37c84f9aa95df51) **FAILURE** in 11m 00s

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 418 at r3](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42#-NoWz9u10MxsMFrEObGy:-NoWz9u10MxsMFrEObGz:b-d3ewic) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/5214d8b27ff7ba063921b1cd60b6464725c5a210/graminescaffolding/builder.py#L418)):*
> ```Python
>             'frameworks/{framework}/nginx-uwsgi.conf',
>         ),
>     }
> ```

Unfortunately, those `extra_files` are needed (here and everywhere else). In JS, they should render from the common template, which is OK.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/1e811bd3d99f471486fed6a5ca5a80d8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/901ef1ad01584cdb993fc9a577d8d948) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/68df98e7d1c4473e99b0dd7a2e2e66f0) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a57864c6a0f24df99c625cdd782051d6) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/1c3c5a36acbd486f80bc651d5e452ff7) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/50cc29279f504015a9217de0b24e2be0) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0185d2d42ba94ee894d7f71ee78f88b8) SUCCESS in 3m 10s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/02a6ae92715445c484e502389feef3c1) SUCCESS in 3m 52s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/c90e8cd744bf42639884131c37a127a9) SUCCESS in 4m 17s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/afecc79dfd0f439a96eab35461d8ca8d) SUCCESS in 8m 09s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/f4efbaea81914b4a8893a3807391e073) **FAILURE** in 7m 58s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/dee6f3bdd0164e7ea432590aa7d078c9) SUCCESS in 6m 04s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/08bbc3d26a654f9caa44d853195e9549) SUCCESS in 17m 09s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/3ff2beedf7b140a5843ae9b1e19a098b) **FAILURE** in 11m 11s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/2abc1a06428847e99319365fcd887fee

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/54d9f977ff7f4a33a0d16460ba341637) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6f0561fdb2ce4758ba9d2a4a19980e02) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b9fe22cb652f42ed8ca3c97096b5ab00) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/efa07ec4e1144b39b4875808fe0e099f) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/1554377332474c7899ae0ed8146199ab) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/8afb4449f04a4ad8bb7a0658f1d5af4c) SUCCESS in 4m 21s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/35ea33559f50402981eceea6bd8736c7) SUCCESS in 3m 35s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/5d3a7cc66bac4df4a843b2ceddfa094e) SUCCESS in 3m 55s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/f9ecf88da8aa4f86a3647a7fb1c461c5) SUCCESS in 8m 08s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/eb7de80f14ef4fe89bf172cd752d946c) SUCCESS in 7m 32s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/34d625d35d634fd3be9bfdc5510d7807) SUCCESS in 7m 13s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/0208e2ff9522416f8e808cca940697ce) SUCCESS in 15m 00s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/188411abec0846568e464fb469ce3f3a) SUCCESS in 12m 26s

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/42)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
