### PR TITLE
run: add information about ports

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/25c68d9ea5524b098232e211004a36e8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/58e7ba4f22474c0386395b03db06cf5f) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/66b78bf776504314aa6658f8fb1fc0d7) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b8184d5a225a408a9859ecabc77d2516) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/b9824ff4bd5a485f81a56c8f4dd9c193) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/de89434ba44c44f79842225dd254693a) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/ab0923cfe36146fd8752b4256f758996) SUCCESS in 3m 03s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/ef3afb42456c4996ac51f1c51c9a8e9e) SUCCESS in 3m 15s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/5c512d1d459948db94b0b0b9d32d8af6) SUCCESS in 4m 44s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/0c2a173ddb334bfb88d006a7c163a72d) SUCCESS in 7m 54s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/a40ddbe3d009407aa1d6d95dc096f855) SUCCESS in 7m 47s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/dce5e3ed58c945dcac4f21c588cc8850) SUCCESS in 8m 17s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/6e8969af235b4114b9764a1a87543abb) SUCCESS in 10m 41s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/38a97ef7c9cf489aa45bcbc7e46ee4e5) SUCCESS in 10m 22s

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @oshogbo)

___
*[`graminescaffolding/__main__.py` line 77 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41#-NoRw99a7M7oHAQ1NLUv:-NoRw99a7M7oHAQ1NLUw:bq3r56q) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/73346da42114595cd4545820660a13173b9b3f89/graminescaffolding/__main__.py#L77)):*
> ```Python
>     ]
> 
> def run_docker(docker_id, *extra_opts):
> ```

I'd prefer if this was named `*args` as it were , every varargs is named `*args` (and `**kwds`, respectively), everywhere.
___
*[`graminescaffolding/__main__.py` line 203 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41#-NoRwTMA3-MVyfTG6SqA:-NoRwTMA3-MVyfTG6SqB:ba7yh4) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/73346da42114595cd4545820660a13173b9b3f89/graminescaffolding/__main__.py#L203)):*
> ```Python
>     Build Gramine application using Scaffolding framework.
>     """
>     docker_id, run_args = build_step(ctx, project_dir, conf)
> ```

Can you refactor, so that: `print_docker_usage` accepts the result of `get_docker_run_command`, and the command is derived here? That way we can dispense of `run_docker` and we will just call `subprocess.run`. Maybe we can also inline `print_docker_usage`.
___
*[`graminescaffolding/builder.py` line 360 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41#-NoRxSBP58ddjT77ySO1:-NoRxSBP58ddjT77ySO2:b-5qp1f) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/73346da42114595cd4545820660a13173b9b3f89/graminescaffolding/builder.py#L360)):*
> ```Python
> 
> 
>     def run_args(self):
> ```

This getter is unneeded you can just return `self.extra_run_args` in `build_step()`. Or have `get_docker_run_command` be a method of this class?

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/aa3010f112f647bd82760830e260b360

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b000d503a4c34ba1a03b257bd10ab716) SUCCESS in 40s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/4c36883b6abd4f08b5454952461648e8) **FAILURE** in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/5eb8b176c9ae42b5b9fb2dcfc6ec03c1) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/568b6d738a36429d8c328c59f020be61) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/a10bc21f248249f9887c6540c828da4d) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c545b872063f471c835e26312dc2147a) SUCCESS in 3m 29s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/a9529f4e43a24220b48a0a09222d92be) SUCCESS in 3m 46s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/cceaf4bb92f84e25a208567b032e3de3) SUCCESS in 4m 00s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/bfa8d36cc09e4852a13736a4bbb88f84) SUCCESS in 8m 20s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/c16935779cc0470a8105c270c2e133cb) SUCCESS in 8m 51s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/f724108507394e0987eb0499eb907ccc) SUCCESS in 7m 34s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/b6b3b4c6e704461da4ae716008822d39) SUCCESS in 14m 23s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/38ea94f4afb64570ba61aedd96d2ba80) SUCCESS in 12m 19s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/f74bb3b06caa48f59954a6412e3db184

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/58b7270038c64a159bba074ea30aa5ab) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/132ca472904a4336998e5a3738e55054) **FAILURE** in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/39cc0056dad749b8b1b3636dc5b480b9) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/88fdfae322ab448ab3a2765deb833f63) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2cc201d09ddb43d188d6b37126cee895) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/47324d40fcd64ee5a7ddd335692b7f07) SUCCESS in 3m 19s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/a870e84268ed4584b12336719e4ca179) SUCCESS in 4m 52s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/9fab2981206e47ae9549a4135428b52b) SUCCESS in 4m 56s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/3a53be59b3b84ae98de6488882ffb348) SUCCESS in 9m 42s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/e3dfb98fc402467bb1b9bf1f1723129d) SUCCESS in 7m 50s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/b35fb54238b944f9bc73821300fa1377) SUCCESS in 5m 23s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/1f8cea2720a7447c8aa3466b403f9166) SUCCESS in 16m 31s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/62cdf89194d24abf82c3cdb8031dad94) SUCCESS in 12m 08s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/9513fe30dbaf48d09c9ac38b77fd69da

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/5f02db5be984466c818c3a53c148bc17) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/005d2431c438468289434dd1d4130a00) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a7a9a830b4b74bbb96cb453ccae36421) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/97a122f026c445a3b6a0a2579101c6e0) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/cacb88e95ddf41bf8fe997ad9b38212f) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/281e79c86d07494ea32f419a15a97dc8) SUCCESS in 5m 19s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/d10d05d58e644d49975b7eeaf40eff44) SUCCESS in 4m 05s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/563c94c968bc444eb752b2dfa00fcbfe) SUCCESS in 4m 01s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/c0dd502b00e34a11a13f7714144a4e3c) SUCCESS in 10m 00s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/8086bed8158e40e9b8efc3fa3bbbdfc5) SUCCESS in 8m 48s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/67eab915316d4f31bc71e63c9b244c1d) SUCCESS in 6m 07s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/cc7daf968ec143a79660686650cc61c8) SUCCESS in 14m 37s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/7848ab83b547473ba8695b3c2b2adb64) SUCCESS in 12m 37s

**Review by bsulich2 — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41)* status: all files reviewed, 3 unresolved discussions (waiting on @oshogbo)

**Review by woju — APPROVED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/41)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
