### PR TITLE
Add passthrough environments

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/36)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/d031582aae6245b5a7e499f3a9f5b151

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/336b1b9c5e3643d18744b404c1649419) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/3374c98ee56f48cc829e76684cd00ced) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/1af1d4dfc9ae431a998a4f397d5808d9) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/98295be6072b4ee3885a06fd1e904051) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8f732b0de5884e8890c2ac6d9c9bb814) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c05c2b2afc314388ba35cb26ec8a4a9f) SUCCESS in 3m 50s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/d958daff1bd1444086e29ca9e5ac13f4) SUCCESS in 3m 53s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/816809dd779a42eab49d4df70ad621bd) **FAILURE** in 3m 09s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/1d6a3bcbd7484601a2ac9f534f0919be) **FAILURE** in 1m 49s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/19dfb20a991b47db86a232530d5decdf) **FAILURE** in 2m 41s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/a2f6e5578e9a455aa8c0a93e5912bf56) **FAILURE** in 1m 41s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d87113b33ea64c7c8dd58c7db583405c) **FAILURE** in 1m 37s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1b5eb876dba743e6b1fcc7b5e5599d9f) **FAILURE** in 2m 04s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/11a3ae010270425f9c970e2ee36014c8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/7b8df4a26ff54f93a58cd471e80d6fca) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/3119dba6313c48d0b77fa3f7132cc988) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/837a1b247d694fd0829c163c206837aa) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/8ee93262b06b446fb5902aaf6973351b) SUCCESS in 1m 08s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e6871aad6e3440f7bd42f04f63a5fb50) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/7bba30e1e147448c95a0bc6d870c8f1a) SUCCESS in 3m 00s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/eede35351711482199bdad9b1ec427af) SUCCESS in 3m 54s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/ceaf5f7432374660ad1c1cb1be526cd5) SUCCESS in 4m 32s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/4dae023a26a64914878cf1f1877998fc) SUCCESS in 7m 00s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/ed27e464c487498396e3cb90715ecd84) SUCCESS in 6m 59s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/25d9356d55274aa49cda4610ebccc33f) SUCCESS in 4m 26s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/80c68270a0004dcca26a4ef019f59f52) SUCCESS in 8m 45s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/ea1afc31c73447928865fe170a266727) **FAILURE** in 6m 05s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/ef89d4710b21427dbf616c537df317e9

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/c125ceb9c9b549c8bc3aa110addd58df) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/7fc0738cfcc64cf9bf441816ff2c71ac) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/f20287dcbdd6447490a0d7f20912758f) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/fe46021c14d349b4a8c1de687bf3e0db) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/5d3c7084c5664e759a19a8d8c7f5b309) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/dc3817792ad54894af6f01b46cd4a843) SUCCESS in 2m 57s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/912fd1cac39142acb43bc3489d269308) SUCCESS in 3m 08s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/c46ac1f957164c10b79a47204b39d11f) SUCCESS in 4m 04s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/c86e49806bf34f2c92b2dd48feb444af) SUCCESS in 6m 30s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/bc5e6d7c6d3e4ebb8e42322dc4c7af7d) SUCCESS in 7m 06s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/cb0f545da89947a78f37158ac65cb9a4) SUCCESS in 4m 31s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/227a4dedd0c84b05aebe893af6815c67) SUCCESS in 10m 31s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/690f9e2652d9478cb6fa1f7ac32e4bf3) SUCCESS in 8m 52s

**Review by woju — APPROVED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/36)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
