### PR TITLE
Add passthrough environments

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/23)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/abeec6cd15464f6388e65280ec6acbc3

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/d0a036463f424663a6039f7755967ec1) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/d36cf73e88be493ea09f2ce757fb8ffd) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/093bdae010e64077a8626843daf89590) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/58d457deffe34047a09c546354026272) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8af7ec2549804b08ae8c7e109ddd8332) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/e741c792b4644db39c1cbd9e33eef37d) SUCCESS in 2m 41s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/38f7bdbf61164b07b6d8dcefe3f5cc25) **FAILURE** in 1m 57s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/1123fba431134757b0c7a56d8d56f055) **FAILURE** in 2m 16s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/6335b21c3f2a449bb9879974cb0f87dd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/690586d84b5f4c78a242992174eb3928) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/7cea5071aa3c49efb4009f32622c053b) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b7fcb0af83054988a7c3cf3268889f16) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0fcbef918b684c11972fe019f84364c6) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2f97cc30e3504c5ea17a68a065a13006) SUCCESS in 36s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/e27b4b2ab5cd41d1bbefb539248aa196) SUCCESS in 2m 39s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6af914b076754d2b9d674b58ddf7b857) SUCCESS in 2m 55s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/012423c17f174d30be86cd9e962c25c1) SUCCESS in 3m 01s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/38fb7315992a4d77a7467dfc51943a3e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/874ece09daa44b62894bd3b4c7f0aedf) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/25ece755339c469eb9e121e0b2873e36) **FAILURE** in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/47e0dbcb178a40778615bde58192381c) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/67694e1312794cd99dbaca70336829c6) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2a430072de4349809a37d8fc6e127ade) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/060703e6dcdd45b9b7ad3914dbe42337) SUCCESS in 2m 35s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/17d2abc72cae4dff85d58675afc55931) SUCCESS in 2m 42s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/5afb240a5a234cfbba9ee852e805b2d7) SUCCESS in 2m 57s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/6092fcac8a4d44ca980f65c79aff1cef) **FAILURE** in 59s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/8479b09816fa42a4ac4c7beba9bde82b) **FAILURE** in 59s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/16768ffb4c9f4f3fb35662727381f2bf) **FAILURE** in 58s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/4c2e7bd93dc54b858a78aad7527a4c0d) **FAILURE** in 1m 01s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/05494d91041f4250833f6973021e128a) **FAILURE** in 58s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/cef7a565f04c48c1852868c4a039d6d8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/19088fc4ae12487391dae4f8c23c8d73) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/60ef33df48ae44eda80fab3f45146524) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/85654fbb5c244a3490833fcc4ec20911) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0f1771a300ce4f298f0ce124e176cf2b) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/070734d080bb489bafa8cb09a7ae0a5d) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/ca84f0fa6e8440558940a39a01937acd) SUCCESS in 2m 37s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/542c7d9ff76e48ba994fb69bbc68e16a) SUCCESS in 2m 46s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/c2e8b8ce8bbf4e019c10c8e7f139fd00) SUCCESS in 2m 58s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/b7905fd68f9b41ef86c5d1095a27931c) SUCCESS in 5m 05s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/b8bacb9a20964a5798006878c22ff3ab) SUCCESS in 5m 00s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/790a45504f714facbf6126623a3ef320) SUCCESS in 4m 09s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/7cf74cb3ada1492692231ddeefeaba3c) SUCCESS in 8m 34s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/4d1ac13ab03b4b27969a4cfb2944988e) SUCCESS in 5m 53s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — APPROVED** [review]
> Reviewed 4 of 9 files at r2, 4 of 5 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/23)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Build canceled.

**Pull request closed without merging**
