### PR TITLE
Fix quickstart

### PR DESCRIPTION
**Pull request by oshogbo**
The build step requires context.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/24)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/f8bfdeb699f24568bf080ce82cf68740

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/13bd90c2972248eab683e1754d8828e3) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6505e84a6d794339b942d2c85157b2a8) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/ed93a60f27cd468fa992d15ac4ecaf6a) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/2daca673bc6d41ecb5b3ac27787eaf8d) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8284b803ff1949eab12b03c93e56d593) SUCCESS in 40s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/4aabea5ad787483b93fc65c261784af5) SUCCESS in 3m 45s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6b3ca09136364468ade11ceb366ee917) SUCCESS in 3m 25s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/352f241f583b49a2964941cd0e45f0e9) SUCCESS in 3m 33s

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/24)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/fbd71d9b97234fbbbb491b231293f41b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/07a733ce3f614e4fa0253c61c2494acd) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/4aaa1830f1e34622b8fe905eea440d88) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/fa5acfbb8f344fd8b6793f86a953666c) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/153279c8a0d3466694c8abdac56b22fb) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/13ab53b4b84a4add91b6750d3670939f) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/23ca946e6c804091b1690bb22c594038) SUCCESS in 2m 39s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/62c97bc1695945bda112730b51ed9603) SUCCESS in 2m 51s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e22837aa17f147d4a83855ddb1a42576) SUCCESS in 2m 59s

**Pull request merged**
