### PR TITLE
Use stable Gramine 1.6

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/35)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b81f8a967cdc40ffbc62efe50aae09bd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8b16d6bd4d3e4bc9ba651174965ac47c) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a7ff3d4365a74db780bb08866ce53d92) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/475817594494482387863ef90f736e61) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/4de585045b5845518e1a7d269212022e) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2d1272e007fb43cd857e42ecfc1be114) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/791eadd8ee54462783259ce7562645c0) SUCCESS in 2m 39s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/3c86a039079a4db5901b8b6441438191) SUCCESS in 2m 58s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/9c2bf1c0b10d43c5afc346e1ea5f1714) SUCCESS in 3m 00s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/2ab7402c2c6747dda38a32587cbac1ad) SUCCESS in 5m 22s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/f6db336b5d814a72a65b4d98c8e5a3b9) SUCCESS in 5m 20s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/ed227cb9f19b47d386568f732901f5c6) SUCCESS in 4m 24s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/84b8495bdf044d94ae40a5899c3dc426) SUCCESS in 8m 46s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/daf5a0fff2ac43bb84c9866da308f8b6) **FAILURE** in 5m 58s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/f835015f061142008d0e4f21cd0bed9e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/4ac3a3e4961442c9a830109f8e2f411d) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/da8887eeeb2c4581ad87840c98d3eafa) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/0cc7ce5e990648bbbee276443e9d0fdd) SUCCESS in 38s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/02439332996243c1b943d770bf9ab30f) **FAILURE** in 56s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/f90a1747355b41a08fbe7ff66be98d86) SUCCESS in 37s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/b6dabcfa6f6a4a3483545a55be7263d3) SUCCESS in 7m 50s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/54e99e79c1a04a7182d999a851979665

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/34ef8a3b43b24a669a9434b02ed7d46b) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/338215bc10184ac395c2e8fa90cd0fc6) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/4b55a4e52dfa448a9377b1d162877774) SUCCESS in 38s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/5753896fa6454336b2413fcf0c37f9e5) **FAILURE** in 54s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/84af2b9a03544a19850e11667ace3eae) SUCCESS in 37s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/e4891145aee34ac690fd47f39d3ada13) SUCCESS in 8m 19s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/2017e9d71b304928a43c4c79afc5e522

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/fb0de2dc92774515b6eab8362653574c) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/5439bd8c9984491598d2458297df3a37) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/3a0b4685ac5e47b4b0584040ec344934) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/1581eab00bb640e48554af2761dd14da) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/a03f3091fc534d6f84354f3338d3480a) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c65ff1e14b2b46a2b754fc9ef78d0da5) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/91b571669d5c4fec9ce85bfa0d9bdbae) SUCCESS in 3m 09s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e0301e4a08cf4c7a85e0851f6b698264) SUCCESS in 3m 53s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/193a04da1831412aa4ab161dec2ad992) SUCCESS in 5m 55s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/ad76f2fc873a44de8cb8b702a732faee) SUCCESS in 5m 37s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/96c3de89061e4cc9b7c3e6a9dfd249f1) SUCCESS in 4m 00s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/3ebce024d43241499d52af58700b8274) SUCCESS in 8m 19s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/e7543fd13d1a4b1c8a902c1b0e76fad0) SUCCESS in 6m 10s

**Review by oshogbo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/35)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
