### PR TITLE
builder: sign outside of mmdebstrap

### PR DESCRIPTION
**Pull request by oshogbo**
Signing in mmdebstrap is essentially impossible, because:
- in --mode=sudo it attempts key from /root/.config/gramine, which is not what we want;
- in --mode=unshare $HOME/.config/gramine/enclave-key.pem is EACCES, because unshare does it's job before hook gets to run;
- in --mode=fakechroot some exotic buildchains may not work (i.e. dotnet) which sometimes does not link against libc (fakechroot works by LD_PRELOAD-ing some hooks that mangle paths in file-related syscalls before offloading to "real" syscalls).

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/32)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/1a2bf5ead3ca4b40b2fdb43fb721047a

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/099a2e98f3364f22a7e9f6f65b8cef60) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/bf40c63d8bb84695bd830edd409449ed) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d17e810e554741d2abeb0f8d5c5efe71) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/3cc07d37562f4a478ebced457ea38cb4) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/10f18584d5f04b72b73402d8ede81fde) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0fe2878edf20465da3212c296d09174c) SUCCESS in 2m 44s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/93c61b51f382410cbef2757f279880b6) SUCCESS in 4m 18s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/9cb53cbd4c27462180ae5e25c776bcd3) SUCCESS in 3m 17s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/7172350082464d41bca6b9be3e03cfed) SUCCESS in 4m 15s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/39e78420d7ca49efb3d2465b787e142e) SUCCESS in 9m 18s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/490dd54c7bb84526b6263d77601c7875

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/a9c19a48797b42d0a56a6f3091d08f42) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a07ddc7d815a4770857be7477ae51de1) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/0f0d6af130d048a39408ec4c9469ad9a) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/72bcdc7f23ac482daf57bd67cce90a8b) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/ce324f25f58e41f488dd896107acbb5d) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6b066d386f9d4c54b81ac5c2ce69fe70) SUCCESS in 3m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/d177eac9a9b74dc6a09dd9319dbfdb89) SUCCESS in 4m 23s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/4ed6c59417c4463a8b38fcd22f7d23da) SUCCESS in 5m 01s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/f8970e82ac734859bba7b2364e9e81a1) SUCCESS in 6m 42s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/9c2f49a73b5e4476be4418089475a3ee) SUCCESS in 10m 09s

**Review by woju — APPROVED** [review]
> Reviewed 3 of 4 files at r1, 6 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/32)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
