### PR TITLE
The listen port in nginx.conf is 8000

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/8204e253786d4c8d889ea284d063750e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/0a0617bbc23a45aeb5122eca8a2bc51f) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/a9adce892f254489a376628f36f175da) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b5203b9052a04535bdba8578c1fd3978) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/d85af6168eaa4e8d8b9498489c5431cc) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/cdb82d34659b4a6ea150cb5294718909) SUCCESS in 1m 13s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/1fb9e90c0a26443997e29987209abf3b) **FAILURE** in 6m 28s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/ece97f3f1e20473d891b79ab98cc830b) **FAILURE** in 7m 03s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/bc8e2eea412b4ad5b907ce19564c5276) **FAILURE** in 6m 33s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/0f0f1150001440b69ffad265860bcce5) **FAILURE** in 13m 35s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/8bb850d7895b4f6f8fd3c4b27f7b5191) SUCCESS in 11m 29s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/e3c3f177313045ccb59b9ea9ee98889b) SUCCESS in 9m 56s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/71e9bd71d6484dc4aabebb2924f8909f) **FAILURE** in 21m 20s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/6dd0f1cbe7d547cf8fbc09c48fadf9f4) SUCCESS in 20m 24s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/4857723012b2498ab80aa1116a14de62

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/11fda1d55ab44b6b9438023f379e890b) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/5da783ac3e4b4b8f940f7262a9f41185) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/dfb5c996547445468176c8a35b52f7bc) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/09451c740b274c40b5a04802e15779ef) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/0277e17298a4445b9cb0eef711bb068b) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/e5e1b474773f49cb9ab389972d726f4e) **FAILURE** in 6m 14s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/b6240a16223a49c696d405fac5fb9811) **FAILURE** in 11m 11s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/83566e3539a54b869cbfe8be202b4c1f) **FAILURE** in 6m 18s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/f0d08fb8fe504dbaa5a2f1cb2ffd2a4a) **FAILURE** in 14m 12s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/e99dad42dc1c44e69aefb67025e14f47) **FAILURE** in 14m 15s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/3f0d40589ab64935b1ea97c578c65b2c) SUCCESS in 12m 25s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/7b0515f81dcd46e388ca53d28215253d) SUCCESS in 23m 19s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/5bc8b2435d19409ca9a7c80724b8ce18) **RETRY_LIMIT** in 14s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/ed454789b97344d5a40231072b5414cb

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/26e4a8703c2945d3aabbd76d0f0336ac) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/d55b0280d88748539e9c4d6ce1ea2f83) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/fb03f8a4dbfd47e69464462d40300a3d) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/87f54101b5584319928a96c061128e8a) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/ce3e24aed2754dcabb800eb45371f042) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/47ce280ff0204e0fb41a8b738494ba1e) SUCCESS in 3m 14s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f5d888475a0549ffaebd9117d5d41c72) SUCCESS in 6m 19s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/bd51cc8e0807490998b2718b5e75afa6) SUCCESS in 4m 05s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/cd27a75dd14e4c9e902bc877bc2e0bf8) SUCCESS in 8m 33s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/fe42055146244d8a9b8aedf6d4144c6d) SUCCESS in 11m 24s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/be77987b2e2447098499d0bed1ddc6cf) SUCCESS in 6m 40s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/adc63d5576504e228948802a3c833341) SUCCESS in 20m 18s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/3ed9ca504ffe4ce3af1af121803821ba) SUCCESS in 12m 04s

**Review by woju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 431 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47#-NpJspCW5tnzm-p3UBwT:-NpJspCW5tnzm-p3UBwU:b-x7lto1) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/602fd0bd30be6ea94fb9b2a095a35e549dd85f26/graminescaffolding/builder.py#L431)):*
> ```Python
>     }
>     extra_run_args = (
>         '--publish', '8000:8000',
> ```

Can this remain 8080, and port in nginx be changed to this, for "IANA considerations"?

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http-alt

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build canceled.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/66b810a5cf5a4b3ea60843879e43c13c

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b2427412c57a4348ac9a7d3034c52f6e) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/b191711952964e599b82d275cf39d2d1) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a09e97e5205042ee9df90a11c40bad21) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/4e1b2fd3ae24477792898c17510777ab) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/1020c690a4aa494aa30f03eb0642f0ac) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/e6f7a20bcc7f44a9a2df7238a05077d9) SUCCESS in 3m 26s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/e4ea8cc73a9b4242bd87884211a04b04) SUCCESS in 3m 06s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/53b0d7db521942fbba982f8ee5e2dbb2) SUCCESS in 3m 18s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/2ac1928752ac40b6a5359d6a9c74d929) SUCCESS in 5m 35s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/eee1f6f549164e33a1a4ab7015b5ebc5) SUCCESS in 5m 53s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/a06a7ee255b94cd8b8a98130b9e48cc1) SUCCESS in 4m 59s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d87623aec27141c58983ad3c5ca0683b) SUCCESS in 7m 51s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/555b66dac6404594ad5d3511fe2b139d) SUCCESS in 7m 02s

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`graminescaffolding/builder.py` line 431 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47#-NpJspCW5tnzm-p3UBwT:-NpKAwxh9Die-biJckqa:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/602fd0bd30be6ea94fb9b2a095a35e549dd85f26/graminescaffolding/builder.py#L431)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Can this remain 8080, and port in nginx be changed to this, for "IANA considerations"?

https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml?search=http-alt
</blockquote></details>

Done.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — APPROVED** [review]
> Reviewed 2 of 5 files at r2, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/47)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/7b268bb770bd4dfba13f08c0c4c58313

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/450f542daa06428e88539ca9f2edb720) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/143234c94c834f2e83bdeccf35032a24) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/8500f6e778584128ae1bc84dc41fa728) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/20a5d1b812c644e79e6b5f6d54c861c1) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b41c88b2d4f1401ba19b2349cda9814b) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/9a63090bb77841e0af3708c09b16e41d) SUCCESS in 4m 32s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/446cae539cc5443d9d200de5828050bf) SUCCESS in 6m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/daf875c94894473a8a6a38ccb8b58505) SUCCESS in 4m 48s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/6109d2805a6242e994a221d6d2605cce) SUCCESS in 12m 18s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/90c6ad4fcf504e05b42dc5828c85a5ed) SUCCESS in 11m 50s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/86f3a61696a64290b67d59bf0ad56bd6) SUCCESS in 9m 22s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d6cb78fc00174659a6e6de9463e06e8a) SUCCESS in 11m 53s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/83d3aa1843e64c719b0730ec485bfc8c) SUCCESS in 10m 12s

**Pull request merged**
