### PR TITLE
Metadata for release 0.1

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/45)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by bsulich2 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/45)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @woju)

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/14e84eab33e448f5aff08424d4df8e7d

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/73ea1bfc88a94e4482bf7f08c925866f) SUCCESS in 41s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/bb014c73c5a84d07abd9ade0374d6ad9) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/149f1ca8605b4bf7ad71b0d44e82eb4e) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/71721ccfd56348dd9d8416cb68b070ae) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/809e1448e1444d19950ecdbfc319d1a2) SUCCESS in 40s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/67270218861649b197246f7a7555bc45) SUCCESS in 3m 12s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/979b45790afb4f308508bcdb92b7b124) **FAILURE** in 2m 46s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/8d012c0a60b440808b21b2581bcb3272) **FAILURE** in 1m 58s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/95bf4652197f4d9a87c40d748ed3b3b6) **FAILURE** in 5m 16s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/ead29dad59464937a88c057f178f7a45) **FAILURE** in 3m 35s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/b9d59323c2734378a9bb30ee85e457f4) **FAILURE** in 5m 14s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/a45cfbda8ef747ee9c0eea78d5276555) **FAILURE** in 3m 24s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1b4654e0b7db4db88f06d8ae1b623ddf) **FAILURE** in 2m 07s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/6e792b24ddbe4c33a50ba78678ffeb51

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/fee00ebbd0b14b77b91ab78ed1c96788) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/9be49f5b67df4d48b88e01682e37ea6b) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/9c42f530686c49028c24854161b73be8) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/114e86a3535448d5a9ad704769d78f12) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/17decb9be1a043d8b04854fd26c0a9db) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/d3400e6df7ef497e9caa912d1ac4ee52) SUCCESS in 4m 09s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/88e8db81c59a4e369fcabf7e28d9128c) **FAILURE** in 6m 54s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/c5d485bdb6394f17bb13403b36f702a4) SUCCESS in 6m 02s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/96d0e5eb1f524f4d912c4a70829d3e19) SUCCESS in 8m 56s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/51e5e9142c4d420280b019e9aa1aa505) SUCCESS in 9m 07s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/8ddf7a775c5444ceb7dcf0df74d191fa) SUCCESS in 6m 29s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/ccf5b9490a5845ccad9df0e80547855b) SUCCESS in 17m 42s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/2bfe119a1f434bf19baa4f76b78154e8) SUCCESS in 13m 44s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/f60e4d7f6297486eb871b32c252828cd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/9a0c2cbf17e64c0886ca752f4dd7e8b0) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/762d643264644aabadc8522e367917c8) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b85744f648ab4d2d8eb4365a53669af9) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/4ecc33f50e2a4393b27c526f5b2c12db) SUCCESS in 1m 08s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e4259e8409a44690b5b0e0597c8b80d0) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/b301c909239142d48f1ef1c3b40541f1) SUCCESS in 4m 25s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/1f36b47ab19f45daa5f795a581c77e32) SUCCESS in 3m 44s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/82dc93cb6aaa4109b8373e9b0f28384f) **FAILURE** in 6m 04s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/d287b95550f1452b9e42d7889d97f003) SUCCESS in 9m 51s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/726d092fb1d04d1f9d3011ffe7295cf9) SUCCESS in 9m 18s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/36b7d92bd1a74deebf2ac9d77d5c04a5) SUCCESS in 8m 13s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/f7fc6eb702a942f5a065ef3189e42368) SUCCESS in 20m 09s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/a3708c0369a2484d8dd0854f5babe74c) SUCCESS in 14m 45s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/d8906564ffdb471bbd3bdb41b0633094

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/afc0fe5028ed45ccad70e19c57e7fca9) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0c668c9d95ac4821a1bb24f0877d9197) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b27d47bdce2b4f99b2e9b333ff1b6e5c) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/49606f293e924ad6a511a554770a4b69) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/297c212734f84602a7c6e9c12d7946e9) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/4c5cfea77a034cccbfd8c57735f67886) SUCCESS in 3m 49s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/141e28f2b9024a3bb17da21252f7908a) SUCCESS in 5m 38s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/7e60bf385edc4a8f820dbe5c2343a9ba) SUCCESS in 4m 48s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/d13bf90ec20c4c7e829232dafe09aded) SUCCESS in 7m 17s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/74c5935f674a46f4bce6dbd09d89981f) SUCCESS in 9m 16s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/347ee2dfa38b484b88cd06c727348a9a) SUCCESS in 5m 56s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/07e8e071fa7740e5b5e241bb84e7bf6a) SUCCESS in 15m 17s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/6cdbb7f744634bc8859243f38544b3ce) SUCCESS in 15m 20s

**Pull request merged**
