### PR TITLE
Fix MAA attestation

### PR DESCRIPTION
**Pull request by woju**
See commit message.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/44)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/737e96f9ca594c07906fc05537fe406f

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/dc0048d448e9499c85efc2c7fae8ce66) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/ef39526e99fe4f46be01d67eee0f7791) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/88e543ec7ea14a4095284400d9bde327) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/531635c8617b406db0f11a656773d76d) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/167acd9eedb24de89ece84a3e8c2ba42) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/a2a9c55e61734113b7612dc21db880b2) SUCCESS in 2m 55s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/774adef7fc7643d99147991d93bdc818) SUCCESS in 4m 25s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/4f4005cf4eaa452a91a4b9da66a7f51d) SUCCESS in 3m 33s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/93b187f3e1f449f58417ee0e99ad9938) SUCCESS in 8m 06s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/4f44af153bf6476285484a5020354c2a) SUCCESS in 7m 40s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/9be7cb2c6d1b45a780947a3d6599785d) SUCCESS in 6m 22s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/a772711085904e53a8d75262f5a56cba) SUCCESS in 15m 48s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1810b8aced15435a83c023b9d4dd4c1b) **FAILURE** in 11m 06s

**Review by oshogbo — COMMENTED** [review]
It seems that dotnet has timeouted. I guess we have to extend the time.

> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/44#-:-NoVvDCqCFzi0n8BJZ_G:b-96r3o7)* status: 0 of 3 files reviewed, all discussions resolved

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/7b21783b3bc348a7b96f59a3bceab956

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/0f565371e5144e8ebf1e8dc70d3423b9) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/e79615dd3af440008a97fe311e630457) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d424b29502024a9db53bfb08839bab64) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/bfd091be7906421cb0f3cb2066c441e3) SUCCESS in 1m 12s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b1a8ae102c24486a91d582771e4ec601) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c6bf31d54c8c4a1ab8d27a9039ffa35a) SUCCESS in 3m 01s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6fa2ec740aa3479dbd173800d9119281) SUCCESS in 4m 45s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/4c7cc25380d4420993f4c66c8cd359e2) SUCCESS in 5m 42s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/b07a1b174fa74780ad0e9f151d4887d3) SUCCESS in 9m 25s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/ae069583509d41a38bf2e09e14da839e) SUCCESS in 7m 51s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/4295878ba6f1484bb6003f511c4e4e26) SUCCESS in 7m 29s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/a4aedd6c793c46879f129f177b4df4a6) SUCCESS in 18m 49s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1c0b871fc71c41159f5cefdf26f3764f) SUCCESS in 16m 17s

**Review by oshogbo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/44)* status: 0 of 4 files reviewed, all discussions resolved

**Pull request merged**
