### PR TITLE
Add java framework

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/5bc585b6b5174f97bd4c1d4cac412f7b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/6ec6a7f430cc4440bd29a46c303cd6fd) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0a5c64ecb752416aad9dac45746ad621) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/c347b89a34d8441bbeadde13f791ac41) SUCCESS in 39s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/24bc7eef48e84788ade0a4eef9b54aa6) **FAILURE** in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/1157cf112d8745ddb5492dd908ffc924) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/510d30fb1e8b4bbf9ad2f3529c399407) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/031d7a98fa52489b83f953e8ddc74e9a) SUCCESS in 4m 04s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/15c527dbb6f94b2fb1d2b17e031bcbe9) SUCCESS in 3m 55s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/2a3a982e03e34793b52a7ceb23bb1fcd) **FAILURE** in 1m 01s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/349237fe4174403e855ef0692b944e9e) **FAILURE** in 6m 07s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/e6ef95be109648d883f0d05b43f78609

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/1816116459704f2f9802d0f9f945298a) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/826bd1e531dd46a1ba49eba0c47d5117) SUCCESS in 53s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/8bff0debb201416889721739b47d05a8) SUCCESS in 43s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/028612a2372e416b9fd54178a65838fe) **FAILURE** in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/5e62cf32ed5e4d17b6640f2835ffe7ef) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6e5c0716fbef4678af6488b26f8ddfed) SUCCESS in 2m 53s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/4c879b64ee664722925ddf1fc621a221) SUCCESS in 3m 05s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/f7c77ba3a49f49298b993f9a0a98d925) SUCCESS in 4m 36s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/c3a85ace0a96492ebd76eae9e875e879) **FAILURE** in 5m 28s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/ac897843082f428ca228bbdacb4a5327) **FAILURE** in 11m 45s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/0af62f6d21344278935b0200f2b5258a

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/1bd81c611b0f4212b4d1591fd87f4854) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/7e64f4548f0b4550a43389822911d492) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/09f5c8b76ae14bbfade0690a35c82d01) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/707c3c79e8804ccfa88f7b8be611c558) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/58464d26e6134793856f024186a0b423) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/1a93d05c95b940a98b9417e743e14f91) SUCCESS in 2m 56s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/e11bb46d28de4124bfb6fec8b96dea3e) SUCCESS in 3m 14s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/18c4768203464ca3a5f99b48287e76d0) SUCCESS in 4m 53s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/3160b524208542a6a3c7ee5e7d216ef4) **FAILURE** in 6m 16s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/e7acc46dee9747d4a7ac52df783023dd) **FAILURE** in 9m 45s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b51a7a6720c34c44acbde8c3cbd5851b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/099e8429d4164b31aa9e7babfae84971) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/ed48a962805c4f17a16c9e97f50c545c) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/22bf1b583c2b4d50a6ff34c70fd151b4) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/8aee6f8d494142cfba6d7afe2ef67e38) SUCCESS in 1m 26s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e8119b70eb964d39be44e4be6381c78a) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/dc91e2fa56b94de997be8600d27997e9) SUCCESS in 2m 59s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f31582d6c1b940bda0929d709b1ff8a4) SUCCESS in 3m 09s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/8e268f2b13764b06b99090568ef16a80) SUCCESS in 5m 14s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/d1424029561c4f66b03d185855fb311c) **FAILURE** in 5m 25s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/6a0880efa29f44e1b041a50fab317897) SUCCESS in 12m 17s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/47033dd1f06d49f59b3a8c8f25c8d66c

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/acefd9f388944eae8a6d52c47de68515) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/2e2347bea12d406a9879823d6af0a106) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/f38d1d4d523e4c87954619a825c04f6b) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/9c5a809827674bec9496dab4d20377ba) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/088c0b3739234879ba98fbc94bac2784) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/912e7b38f7b545cca2cea2f031b27475) SUCCESS in 2m 58s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/764ed46ae7c44f699e8e95fee3ea9478) SUCCESS in 5m 20s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/7f99a8927fda4f86b177bce0ab28de31) SUCCESS in 5m 24s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/0db1964ea16a4ecebdb43f591d4f2d35) SUCCESS in 6m 35s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/980a59aeb18546af9f547dceb8d28136) SUCCESS in 12m 51s

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: all files reviewed, 5 unresolved discussions (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 88 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06JvQ8MIb_h6gsc0D:-Nk06JvQ8MIb_h6gsc0E:undefined) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L88)):*
> ```Python
>     depends = ()
>     bootstrap_defaults = ()
>     BINNARY_EXT = (
> ```





_Suggestion:_
```Python
BINARY_EXT
```
___
*[`graminescaffolding/builder.py` line 89 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06ZPnEvUhOQdois92:-Nk06ZPnEvUhOQdois93:bs2dc96) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L89)):*
> ```Python
>     bootstrap_defaults = ()
>     BINNARY_EXT = (
>         ".jar",
> ```

single quote for consistency
___
*[`graminescaffolding/builder.py` line 120 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk13ZFqAjVqxgwqm1o7:-Nk13ZFr0P1d6-_lyrof:bg44hnf) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L120)):*
> ```Python
>             file.write(template.render())
> 
>     def _move_binary_template_to_path(self, template, path):
> ```

Shouldn't this be named "copy" instead of "move"?
___
*[`graminescaffolding/builder.py` line 124 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk12zs712k1ZRHpzDWx:-Nk12zs712k1ZRHpzDWy:b16vrbf) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L124)):*
> ```Python
>         with resource_stream(__package__, template) as source:
>             with open(path, 'wb') as file:
>                 file.write(source.read())
> ```

I'd prefer if this used https://docs.python.org/3.9/library/importlib.html#module-importlib.resources from stdlib instead of https://setuptools.pypa.io/en/latest/pkg_resources.html, which is not from stdlib and deprecated.



_Suggestion:_
```Python
        with open(path, 'wb') as file:
                file.write((importlib.resources.files(__package__) / template).read_bytes())
```
___
*[`graminescaffolding/builder.py` line 326 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06mR_43RfmCSZzR6j:-Nk06mR_43RfmCSZzR6k:bs7dh6x) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L326)):*
> ```Python
>         'gradle',
>         'openjdk-17-jdk',
>         'openjdk-17-jre',
> ```

It's probably enough to use `-jre-headless` variant, isn't it?

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: 20 of 21 files reviewed, 5 unresolved discussions (waiting on @woju)

___
*[`graminescaffolding/builder.py` line 88 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06JvQ8MIb_h6gsc0D:-Nk17fwsAXSY1DviIBu8:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L88)):*
> ```Python
>     depends = ()
>     bootstrap_defaults = ()
>     BINNARY_EXT = (
> ```

Done.
___
*[`graminescaffolding/builder.py` line 89 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06ZPnEvUhOQdois92:-Nk17gEq5QAMC_sK1kk7:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L89)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

single quote for consistency
</blockquote></details>

Done.
___
*[`graminescaffolding/builder.py` line 120 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk13ZFqAjVqxgwqm1o7:-Nk17oXD5tGdWptFtQVQ:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L120)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Shouldn't this be named "copy" instead of "move"?
</blockquote></details>

Done.
___
*[`graminescaffolding/builder.py` line 124 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk12zs712k1ZRHpzDWx:-Nk187bHANspxQQi2q6B:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L124)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

I'd prefer if this used https://docs.python.org/3.9/library/importlib.html#module-importlib.resources from stdlib instead of https://setuptools.pypa.io/en/latest/pkg_resources.html, which is not from stdlib and deprecated.
</blockquote></details>

Done.
___
*[`graminescaffolding/builder.py` line 326 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk06mR_43RfmCSZzR6j:-Nk18OCu3XNU2NTAczTM:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/004df98e80e865d4ac682c08893d3ea49d57059c/graminescaffolding/builder.py#L326)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

It's probably enough to use `-jre-headless` variant, isn't it?
</blockquote></details>

Done.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/f859d913e7d4445d80c4105342551774

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/f32daac7caa049fa92490c9078023eaf) SUCCESS in 39s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/bde55527fd374d24a37c9195bf70dfaa) **FAILURE** in 46s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/230f62e346d74ed7b64b35f12bed6772) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/daabf754d3834e61b139c62a6cc5c6fa) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/3aa7b65ea83540f3bae540f1dde970a5) SUCCESS in 40s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/0319f9b4a4b5429087c216e9f6284b4a) SUCCESS in 4m 13s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/e72553852c584e2d9ecd6f4edc114a8b) SUCCESS in 5m 43s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/393b46d854ff40349ac31a2eca8c9877) SUCCESS in 6m 02s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/0e0de450768e4c2399fcea0239eebea1) **FAILURE** in 57s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/f958b1996cb44450b5514190ad0d721b) SUCCESS in 11m 53s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/686fea5302d84151be6d328978539e22

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b558fa8d60954bd39e78c60306568157) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/d463fc8444964c739a8b8492f8fdc717) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/7c16f8c7c0af4fd6aef6d2d2e80b0c9e) SUCCESS in 37s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/ed3e29d047c24b83aebfda592a7d0e92) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/25daefa4e44f496ea49b90b4ec56e21f) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/67533991fa374f5d87812cdce60e520c) SUCCESS in 2m 44s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/cd6b1b751a3c479e85089433d7a932d6) SUCCESS in 4m 04s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/35a94eddea77445bbbd2d077f4947555) SUCCESS in 3m 17s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/b73b398fed3c44b2b0ced6b727da2c9e) SUCCESS in 4m 33s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/9b0b4df0acd748968d5ea56385d32e57) SUCCESS in 9m 26s

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 12 at r3](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk1k2GR10OuFdephYXR:-Nk1k2GR10OuFdephYXS:b-rrmht8) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c9569d08fa704be5d414393fe822a5a352befb8a/graminescaffolding/builder.py#L12)):*
> ```Python
> import types
> 
> import importlib.resources as pkg_resources
> ```

Why "as"?

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`graminescaffolding/builder.py` line 12 at r3](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk1k2GR10OuFdephYXR:-Nk6xaxt6LQOG_pc3tfq:b-9waz0k) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c9569d08fa704be5d414393fe822a5a352befb8a/graminescaffolding/builder.py#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

Why "as"?
</blockquote></details>

I can do "from" if you prefer :)

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/75184093a1bd4a50845a50642e2cad8e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/33eabe7531694289b200eef777ce564e) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/563f7b615331473aa685dd66e31ec7c6) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/83b0d63f52584d4e8837b642ed2a16b5) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/5853b6bbb2bb43e0b43e265a6d13a621) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/7427447cceaa487b8a503c5feb6b6ad1) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/de1f1035c0fd468bb0a24134f44e0475) SUCCESS in 2m 57s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/ecbf9f97d5944f6b8455495793adea4e) SUCCESS in 3m 07s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/6ec6c38098c244b1a8d8755a81113ef0) SUCCESS in 3m 12s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/a7386a119a254cc895fb97c72f641c57) SUCCESS in 6m 17s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/6228e1b6969640e49d0b773ac712bd0f) SUCCESS in 10m 16s

**Review by woju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: all files reviewed, 1 unresolved discussion (waiting on @oshogbo)

___
*[`graminescaffolding/builder.py` line 12 at r3](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk1k2GR10OuFdephYXR:-NkGY2bB4np3-ZQlC_xO:bnn8a5b) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c9569d08fa704be5d414393fe822a5a352befb8a/graminescaffolding/builder.py#L12)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I can do "from" if you prefer :)
</blockquote></details>

No, why can't you just `import importlib.resources`, and then below `imporlib.resources.files(__package__) / 'templates' / template` (or `importlib.import.read_binary()`, this detail I don't care so much about)?

Explicit is better than implicit...

**Review by oshogbo — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: all files reviewed, 1 unresolved discussion (waiting on @woju)

___
*[`graminescaffolding/builder.py` line 12 at r3](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27#-Nk1k2GR10OuFdephYXR:-NkHIoqX5YJnfwD4E2Tj:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c9569d08fa704be5d414393fe822a5a352befb8a/graminescaffolding/builder.py#L12)):*
<details><summary><i>Previously, woju (Wojtek Porczyk) wrote…</i></summary><blockquote>

No, why can't you just `import importlib.resources`, and then below `imporlib.resources.files(__package__) / 'templates' / template` (or `importlib.import.read_binary()`, this detail I don't care so much about)?

Explicit is better than implicit...
</blockquote></details>

Done.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/9d194b9f0aef4d2a97ef64ee75807d5f

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/237bd73e67fd4f209ca5a812fbee29d7) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0ac3933ce0c44f149f5789065ef2a456) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/a2b4900d4cd7487b8febdb5559af5d3b) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/32dbe4892ca2443b82d11f0085568361) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/8a8b20f918a64437a37c2cc4456ae592) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/1fdca245aae241a9bc2505671bdb54f1) SUCCESS in 2m 38s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c6bd3a7ba9b54a2197fd766899ad23bd) SUCCESS in 3m 31s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/789235ca1ccb4aa48491ec46f30afe89) SUCCESS in 3m 01s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/2511a1a7c6e5408ba1f71dc0135dea32) SUCCESS in 4m 30s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/554f51cea18b4e669e61e46cd91ca703) SUCCESS in 8m 09s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/56dbb6bcf5ab446b8b446ad0eab01fb8

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b3801c78a4a24b56bc80e003d72b5c48) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/738e0f414ea94863b9d01cca4c00e605) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/8c613264b7784666830dfae224bcffcc) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/f2feb96fee414b3691df5584deca5ef8) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/ee5feb071e554c5d8ba7241b9036afc8) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/9d8711a5f5f24ee8a95c75fb5a8205b0) SUCCESS in 2m 42s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/e146e3cf9552429e8b7805321a4a4664) SUCCESS in 2m 51s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e7610ce157464f7398a324e9da94c0b4) SUCCESS in 2m 57s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/b89ea14fb8d2436e8567608c11d34d22) SUCCESS in 6m 00s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/52eba68061b8424ca05e9aabc1c30c2f) SUCCESS in 6m 34s

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Pull request merged**
