### PR TITLE
Add express.js and koa.js

### PR DESCRIPTION
**Pull request by woju**
Based on #15 and another @oshogbo's branch.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/29)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/e9fe06c8ea92475484f0e19c42bd01cd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/07a2e7a0a14e40b5869c47e3f52160b2) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/ed742ce8917b489fbced8f2c4118639d) **FAILURE** in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/35a8e91d923b48b4a1cdcd5825905736) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/53acd9877c364d52adfcf0d102b3d9f9) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/fd1f62dbd3f44140a50a4f8a08670b44) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/394336a47dba48c48dfa6e89321493bb) **FAILURE** in 1m 00s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/3d551113a4d74082b604bc6b357b5cb1) **FAILURE** in 3m 08s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/4262c056210d44169a412d05a1fc9d6d

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/512a0b4660a94631b7f180ca1a8e4d4e) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/db1e660dd54840b1a02b41de0f169f11) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/4b2896b78d744519aa56d9ad4aa5a9a0) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/b610f314c68c4eb88aba12b57f74f0a0) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b633d1133fd441c4b067f1c4161c4059) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/98fa82ed2f9341f58811fcc799576855) **FAILURE** in 1m 07s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/d10eebbd0e7b47fc8b5f16d98bcf4b72) **FAILURE** in 1m 17s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/840b2d3f443441e8b174595fa0c3b98b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ef11eb420afc4bfab9d676a76ccc4fea) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/871e74cd68ab4c668ca0e27f9d0819dc) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/eb9f5aa61ea8403fbefbe70161def1e6) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/cc70e143ca4f4385aeaf6df20646befc) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b90d0b920d1d430eb9745c4ce8a20c62) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/cbb02dd6d8a641e3ab0da4e86aa04e30) **FAILURE** in 6m 25s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/86679bbfab4440b3b78f53b66fcb339c) **FAILURE** in 4m 43s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/94b8b73cae2749d49893572fe8f456af

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/bd3f864d2c2c4627bc2e289cdf667dec) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6d1107578a23480caac488d9e686305d) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/188fa0d125c74a3a94a6007bf6de5b4f) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/7b85eb3db8b2407983dd4e702e22ca6a) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/5e69dfd58a8848ca9e78d1e25e3d47e5) SUCCESS in 39s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/573d9f139d424b30b008c2f37bd6481f) **FAILURE** in 4m 51s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/617695704cd04b5b824cf3cd511beded) **FAILURE** in 4m 53s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/66b74fe1c1674c6da22b763477b3c3eb

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/73b8d5b81b884e05a9a4dcf060c3114a) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/e7ab3668945645c4ab7ee74b644221de) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/e82424bc1da74c39a44ba1432fc34d73) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/73ed1b579b8b4203ba92baf2df9d5012) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2c085dd194e94e4ea4a6915622b9ab46) SUCCESS in 38s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/af3f00974bdb4e1ab7fa3016fe0a4add) **FAILURE** in 4m 24s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/7b799237c2164042812ef3f9035da2d1) **FAILURE** in 4m 51s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/5facf07c234d4005bd10232036396fe4

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ff4ea47f826b4a55b2720345c9bf2d17) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/1de503f981084f69971b6c1da4c99e08) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/972f130e28fb452282904fb38408bd0c) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/c1708d49592d452ca7bffdd11cb70439) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/0bc0e789f97e40b082619a1b8a81cd7c) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/7092dd9c4e864c3b8b6496bf005e37fc) **FAILURE** in 6m 20s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/61f27e5e80e4449797c8183f0c4cb04c) **FAILURE** in 5m 21s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/c079c590506c4b8db627b2fba0dad56c

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/942f2d7de3924d368192b5a8340560f7) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/da53761e0dba4dc3a0ef43e9069c37bc) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/2090ff5e830749e7b33dc4be189d0ce4) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/cc1ac0a8e1574223845bdfd621499895) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/572d9d440da84073b0f3f4d6d7bda1cf) SUCCESS in 39s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/0c0b14d4257d471092147acbbca97cdb) **FAILURE** in 2m 26s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/9f7163d0680748e69626c0af3ffbd5ac) **FAILURE** in 3m 19s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/39d6e4f4d12142b2b34cb02e0dc4224a

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/276b9f9dcd6b424299548eba88ac788d) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/b1081acad9614f3995ffb532011f8cae) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/c82255e4e30044cd8ba0e81b65f06560) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/76b06fe361914070b062b5ee5c891b6b) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2c8c00f1d57145fe81635defffae33e2) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/9181a15118484c3c8f2d04aeef7b09b4) **FAILURE** in 5m 45s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/64a7883dbea847638706dd44aa585634) **FAILURE** in 5m 46s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/caf1a96ec1984344be9cfa4951f90a0e

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/50d7f4c373254e959780ad08f80fbf11) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6c539359a083425c8eb4d9b8116a7cac) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/f4af8f6b636d430cae2dd8729bf0968e) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/20b5e52ad33b4c53833bf99d7419ca16) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/d8ff474044d04fb1b6907e3feb327a5e) SUCCESS in 38s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/aa0f25d29daf434ebb00ba364402ed05) **FAILURE** in 5m 31s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/3f0ea8cfb57c4721bcfcbeadfadc800b) **FAILURE** in 4m 53s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/56415772feca4658a9d9e1fcb71a6784

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/11c26914652f4eecbbaa33bf5fbcedc5) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/aff4aba466cd4067a9ce2dc3ecbffd73) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/e096408a94b9421ab63df90f5ff842a9) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/5bfa5b5fb4774cb0876bb682e98b364a) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/926045792e0b4e4ba7b12001995cf2a5) SUCCESS in 37s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/90e5dfe8caf8407ab6059dcb984abfb8) **FAILURE** in 7m 00s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/f00ed0207fc0490c8b88359fa3182c61) **FAILURE** in 3m 32s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/ce937c4f68914730aba12772f24f23b7

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/e40eb99c04044705a8a2ad6d44973070) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/eac1b3ced54b4842ad04e0d9a2382e77) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d713ac5901a949109395fa69e613f7c0) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/fc8f6ed83a504dcfb98b179f61ef4f0e) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/7994f138333445fab2f72296dcc274ba) SUCCESS in 38s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/3cf2a86d61d74237a9be9dba79020926) **FAILURE** in 5m 21s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/671d39b468ea48ca9dcdbbf70c09c721) **FAILURE** in 6m 55s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/32e45d76685e430d9f0fc6a5a6d1652b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/c4766b14d9bb4404b926260cbc2b192b) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/071983135cad45ae914a50b6d336a204) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/ed365197d1114b10abcaf62806d26b7f) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/9f4e056886e1411391de58d1868c4568) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e31450cadada402886f3dff0bce4906b) SUCCESS in 38s
:x: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/dbe8c1a8284b4d699ba16fec138f92f3) **FAILURE** in 6m 42s
:x: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/cbf3ab9cf7b946a7be3bec596cc7d9ec) **FAILURE** in 6m 54s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/5ee50ac2b009405288fcce5df46e1cc6

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/490a8b5aebb84f8bb05abc29f9f2d8ae) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/7592e704ee2548a2a1297858a046d31e) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/ed9366c8d6b645f3a9fbce3a0342462a) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/3c1a201a8a604aad83d33f23a394de58) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/5a234f2dda5d46e5a8438b1e8854b69e) SUCCESS in 37s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/ad1e2a8f089e4e1da91d14b14796b161) SUCCESS in 6m 16s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/818f577da91f4970b094e77fec12a340) SUCCESS in 7m 32s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/b6b46fb404a24ff7a13749035604cadd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8bc0570f7e614bd1b44f2c382159145b) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/86bc5d9ed52c4270bac186d1e89d2096) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/0bf37a498d6044d88c6fb59ecf0b4d12) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/f8854a3105b24fc188cae2111f418789) SUCCESS in 1m 10s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/6e615fdffc9d4793bd38e892d95e4be9) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/2762d55ae0b6471a92a9cc2cc9f7cd4f) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/51467525f1c6453c80881e0544944655) SUCCESS in 4m 10s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/ce7f1055252d4cdab2c281f2f05e1d79) SUCCESS in 3m 05s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/673e5c02c07c437e81cd34f4de957ea8) SUCCESS in 5m 41s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/793ed4804fd24b63be136fb237880169) SUCCESS in 7m 01s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/d2e767da6d984263ad92ba3072ff356c) SUCCESS in 6m 04s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/361719e2e838464cb353f20d9f25a228) SUCCESS in 9m 30s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/a60c166874264829a0c3ab54e76fc119) **FAILURE** in 6m 03s

**Review by oshogbo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/29#-:-NlNnsne-qW54PjItZ5d:bnfp4nl)* status: 0 of 20 files reviewed, all discussions resolved

**Pull request merged**
