### PR TITLE
Attestation (`scag-client`)

### PR DESCRIPTION
**Pull request by woju**
This tool completes end-to-end solution, adding a REST client that will perform remote attestation before sending the HTTP request.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/5e72e308e458434cac43f4b58bd17d96

:x: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/194ee72d3dfc4eeea647d5a3f5884699) **FAILURE** in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/beefaea130f44491aff67676d513836b) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/fc85c8ada59a4540a716955cb2ee06f9) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/38693f8d52a54acb82ed9d2e3c6c8163) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/31238de9552a42e4b43031a65d44f134) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/b6b2344e09be48e7af3cfbcba7ab7b9f) SUCCESS in 2m 43s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f3e7eca35cc24064945b280f23c4c950) **FAILURE** in 2m 50s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/d3942b036a5c4a8797678bba2b1697aa) SUCCESS in 3m 06s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/9b16533393154752a1dc48298077463b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/386df32265ab4378ae9470d5cfbcbf88) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/2b7ec0c047c1448d8e92afbc6e174b73) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/bd7ea5ad923e4ffbaba31dbe518cdfa6) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/fcbe530c7d0a41e3ab9b2ceeade3908a) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/56529153c46546e48395df9b7920aaa7) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/ffe024b6a9be4aa090c95fc80e57ee09) SUCCESS in 2m 44s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/0a138ee1dff34d36a999e2bd399d6066) SUCCESS in 3m 15s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/6097084a0e2a4ec0ab542efb7b450cd8) SUCCESS in 3m 05s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/2b9374e1bdc2491e9c0ee560461a5508

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/081bbc1740404b1c8eee074e21b1ae97) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/c4ab5840569b464ba816153b9839ba37) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/0da09af63c5f44daa5ca1e7176c1213e) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/e30b3c772b5b48279465c429bcaa0a55) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/a1d7c6e798e147879b40cd300d5ec06c) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/7de2e6a2c8794bf0964cd5efea158e46) SUCCESS in 2m 41s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6ead8e10296840ec8243419a10deebaf) SUCCESS in 2m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/32e3ccaccaf1476da50b61fc5f7235fe) SUCCESS in 3m 15s

**Review by oshogbo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @woju)

___
*[`Documentation/manpages/scag-client.rst` line 34 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Vq3r1BQ2MfNG1Blh:-Ni5Vq3r1BQ2MfNG1Bli:b-jova70) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L34)):*
> ```reStructuredText
> .. option:: --request <method>, -X <method>
> 
>     Use specific HTTP methor, rather than default ``GET``.
> ```

method



_Code quote:_
```reStructuredText
methor
```
___
*[`Documentation/manpages/scag-client.rst` line 38 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5VuGJ9-852S-Digrp:-Ni5VuGJ9-852S-Digrq:b-84vsmc) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L38)):*
> ```reStructuredText
> .. option:: --verify <attestation>
> 
>     Use specific attestation scheme. One of ``DCAP``, ``EPID`` or ``MAA``.
> ```

List?



_Code quote:_
```reStructuredText
One of ``DCAP``, ``EPID`` or ``MAA``.
```
___
*[`Documentation/manpages/scag-client.rst` line 43 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XH2l4Id8h5ymQhpQ:-Ni5XH2l4Id8h5ymQhpR:b-n06l5n) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L43)):*
> ```reStructuredText
> .. option:: --output <path>, -o <path>
> 
>     Writes the response body to this file. If not given or ``-``, writes to
> ```

Use, expects and then writes. Shouldn't be write?

Non blocking.



_Code quote:_
```reStructuredText
Writes
```
___
*[`Documentation/manpages/scag-client.rst` line 92 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5WdjX0a9UYe8qPeMH:-Ni5WdjX0a9UYe8qPeMI:b-vfc7dh) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L92)):*
> ```reStructuredText
> This file is written by :ref:`scag-build` and read in :ref:`scag-client`. It
> contains default values that configure the attestation environment, like
> type of attestaion (DCAP, EPID, or MAA), expected MRENCLAVE and other
> ```

attestation



_Code quote:_
```reStructuredText
attestaion
```
___
*[`Documentation/manpages/scag-client.rst` line 109 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5WDAh1uzlRV093xlU:-Ni5WDAi6jvvw5yX-2dK:b-84vsmt) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L109)):*
> ```reStructuredText
> 
> ``scag-config.attestation`` (string)
>     One of: ``DCAP``, ``EPID``, or ``MAA``.
> ```

List.



_Code quote:_
```reStructuredText
One of: ``DCAP``, ``EPID``, or ``MAA``.
```
___
*[`Documentation/manpages/scag-client.rst` line 133 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Ws5Q1LdMW429chjL:-Ni5Ws5Q1LdMW429chjM:bs6av05) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L133)):*
> ```reStructuredText
> 
> ``dcap.allow-outdated_tcb-insecure`` (bool, default false)
>     INSECURE, DO NOT USE IN PRODUCTION! Allows enclaves ran on CPUs with
> ```

Sounds weird. `Allows enclaves to be executed`?

Not blocking



_Code quote:_
```reStructuredText
ran
```
___
*[`graminescaffolding/__main__.py` line 230 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XeXG7-s2x8TIBGKf:-Ni5XeXG7-s2x8TIBGKg:b-ih6g9d) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L230)):*
> ```Python
> @click.option('--project_dir', '-C', metavar='PATH',
>     type=click.Path(dir_okay=True, file_okay=False),
>     help='The directory of the scaffolded application. If given,'
> ```

I think: `If not given`



_Code quote:_
```Python
 given
```
___
*[`graminescaffolding/__main__.py` line 237 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XkKW-YRNmZnQt-zV:-Ni5XkKW-YRNmZnQt-zW:bl65cwb) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L237)):*
> ```Python
>     help='Path to scag-client.toml configuration file.')
> @click.option('--request', '-X', 'method', metavar='METHOD', default='GET',
>     help='use another request HTTP method (instead of GET, the default)')
> ```

All other options start with a capital letter.



_Code quote:_
```Python
u
```
___
*[`graminescaffolding/__main__.py` line 240 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Xq_e3xjsPUrlFwVh:-Ni5Xq_e3xjsPUrlFwVi:b-dy1rhe) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L240)):*
> ```Python
> @click.option('--verify',
>     type=click.Choice(tuple(_client.VERIFY_CB), case_sensitive=False),
>     help='load RA-TLS library for this method')
> ```

ditto in all options below.



_Code quote:_
```Python
l
```
___
*[`graminescaffolding/__main__.py` line 268 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Yhdz2QJUfBO2eJzR:-Ni5Yhdz2QJUfBO2eJzS:bdt8kip) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L268)):*
> ```Python
>             if not cfg_path.is_file():
>                 ctx.fail('scag-client.toml not found')
>             config_file = open(cfg_path, 'rb')
> ```

I guess you can simplify this:
```
if config_file is None:
       cfg_path = ""
       if project_dir is None:
            xdg_config_home = pathlib.Path(os.getenv('XDG_CONFIG_HOME',
                pathlib.Path.home() / '.config'))
            cfg_path = xdg_config_home / 'gramine' / 'scag-client.toml'
        else:
            cfg_path = pathlib.Path(project_dir) / '.scag' / 'scag-client.toml'

        if not cfg_path.is_file():
            ctx.fail('scag-client.toml not found')
            config_file = open(cfg_path, 'rb')

 ```

In this case you don't to twice checks of `cfg_path`.



_Code quote:_
```Python
            if not cfg_path.is_file():
                ctx.fail('scag-client.toml not found')
            config_file = open(cfg_path, 'rb')
```
___
*[`graminescaffolding/__main__.py` line 269 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5YJyL7KvE6OT_dHyU:-Ni5YJyL7KvE6OT_dHyV:bqm7ceb) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L269)):*
> ```Python
>                 ctx.fail('scag-client.toml not found')
>             config_file = open(cfg_path, 'rb')
> ```

No need for extra line.
___
*[`graminescaffolding/client.py` line 126 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5ZdtL4Nvx44SMNl-N:-Ni5ZdtL4Nvx44SMNl-O:b-ccnej8) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/client.py#L126)):*
> ```Python
> 
>     ra_tls_verify_callback_der('epid', cert)
> VERIFY_CB['epid'] = verify_epid
> ```

I'm not sure what this is. If this is wrong indent or it should be separated from the function.
___
*[`graminescaffolding/client.py` line 146 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Zm265jQcU7omn2vk:-Ni5Zm265jQcU7omn2vl:b-rqxvo7) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/client.py#L146)):*
> ```Python
> 
>     ra_tls_verify_callback_der('maa', cert)
> VERIFY_CB['maa'] = verify_maa
> ```

ditto.

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20)* status: 0 of 11 files reviewed, 11 unresolved discussions (waiting on @oshogbo)

___
*[`Documentation/manpages/scag-client.rst` line 34 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Vq3r1BQ2MfNG1Blh:-Ni5db2MCNXZmghn7t1B:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L34)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

method
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 38 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5VuGJ9-852S-Digrp:-Ni5dkps4vB5o7X_C6fF:b-ugmqaw) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L38)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

List?
</blockquote></details>

Done. I've put the list in the config, to avoid duplication.
___
*[`Documentation/manpages/scag-client.rst` line 43 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XH2l4Id8h5ymQhpQ:-Ni5eCiDBLlFMjiRuVVK:b-uy2wjq) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L43)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Use, expects and then writes. Shouldn't be write?

Non blocking.
</blockquote></details>

Done. I've unified the grammar, plz see if the style is right.
___
*[`Documentation/manpages/scag-client.rst` line 92 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5WdjX0a9UYe8qPeMH:-Ni5dzD02oXcRgV2UF4g:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L92)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

attestation
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 109 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5WDAh1uzlRV093xlU:-Ni5jhkX77zPoXfHm-U8:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L109)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

List.
</blockquote></details>

Done.
___
*[`Documentation/manpages/scag-client.rst` line 133 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Ws5Q1LdMW429chjL:-Ni5effA-cMz5rT2x0Uf:b-25z19p) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/Documentation/manpages/scag-client.rst#L133)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

Sounds weird. `Allows enclaves to be executed`?

Not blocking
</blockquote></details>

Done. "Allows enclaves executed", because the enclave is already in execution when this tool runs.
___
*[`graminescaffolding/__main__.py` line 230 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XeXG7-s2x8TIBGKf:-Ni5epoKDXkvN1SZ9JbL:bon2dyn) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L230)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I think: `If not given`
</blockquote></details>

No, this is correct. If you give `-C <path>`, then it looks for `<path>/.scag/scag-config.toml`. If you do not give this, then it looks for `~/.config/gramine/scag-client.toml`.
___
*[`graminescaffolding/__main__.py` line 237 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5XkKW-YRNmZnQt-zV:-Ni5fGqR-rpyqjagAwA7:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L237)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

All other options start with a capital letter.
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 240 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Xq_e3xjsPUrlFwVh:-Ni5fH4bAh2NdLS1VJoN:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L240)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto in all options below.
</blockquote></details>

Done.
___
*[`graminescaffolding/__main__.py` line 268 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Yhdz2QJUfBO2eJzR:-Ni5fdxa6cDqAXoNVJmk:batq99d) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L268)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I guess you can simplify this:
```
if config_file is None:
       cfg_path = ""
       if project_dir is None:
            xdg_config_home = pathlib.Path(os.getenv('XDG_CONFIG_HOME',
                pathlib.Path.home() / '.config'))
            cfg_path = xdg_config_home / 'gramine' / 'scag-client.toml'
        else:
            cfg_path = pathlib.Path(project_dir) / '.scag' / 'scag-client.toml'

        if not cfg_path.is_file():
            ctx.fail('scag-client.toml not found')
            config_file = open(cfg_path, 'rb')

 ```

In this case you don't to twice checks of `cfg_path`.
</blockquote></details>

Done. Right, thanks!
___
*[`graminescaffolding/__main__.py` line 269 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5YJyL7KvE6OT_dHyU:-Ni5gQGs6GajKvE2_Qm8:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/__main__.py#L269)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

No need for extra line.
</blockquote></details>

Done.
___
*[`graminescaffolding/client.py` line 126 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5ZdtL4Nvx44SMNl-N:-Ni5gdbA97XxhgOhNGvU:brls6fw) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/client.py#L126)):*
This adds `verify_epid` function object as a value to `VERIFY_CB` dictionary under `'epid'` key. After all those statements VERIFY_CB looks like this:

```py
>>> pprint.pprint(graminescaffolding.client.VERIFY_CB)
{'dcap': <function verify_dcap at 0x7f97ded819e0>,
 'epid': <function verify_epid at 0x7f97ded81a80>,
 'maa': <function verify_maa at 0x7f97ded81b20>}
```

The directory is then used to look up the function that will be used (the key is from `scag-client.remote-attestation` from `scag-client.toml` or `--verify` argument to `scag-client`).

Usually in Python, if the function is to be used from a dict like here (not just imported), then the adding it to a dict is done without empty line between function body and the statement that adds to a dict. This achieves a visual symmetry with `def` statement, which is also not separated by empty line from function body. See for example this file from stdlib: https://github.com/python/cpython/blob/244567398370bfa62a332676762bb1db395c02fc/Lib/copy.py

I can do whitespace like in this new revision (single line separating function from dict insertion and two lines separating dict insertion from new line), but I wanted to avoid this. Particularly when you're copying one function as a template for another (were we to add support for another attestation library), you need to copy this assignment and update.
___
*[`graminescaffolding/client.py` line 146 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-Ni5Zm265jQcU7omn2vk:-NiEtD18Da1RNwt4H3sf:bs4q9op) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/79e47b73c728a3ccb9a1d8fb7aebed3794fffe65/graminescaffolding/client.py#L146)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

ditto.
</blockquote></details>

Ditto.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/acb04e3fa36343f5b355385bf97c694f

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/103535569f3c4fd8a4f6e1e2bda61b4c) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0f1197bdfcce4616bf107652ee6fc8f0) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/2792e9064ce7462a82770321b09d8de6) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/9f2f5db98f514b4697fae20ceb2b16a8) SUCCESS in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/433bf1244d95451c908e8f54e4fbf2d6) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/cf609cb56b1d446eb5afaf549a741f9d) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c1effc1a82f44914825592641113c494) SUCCESS in 2m 49s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e6cbb4bd87bd4e438ff7a514a1b43c68) SUCCESS in 3m 01s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/99b04aa2f3b9420490bb28351a349dc7

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/d2bd110f2f6b4c0ca8aa85d33644500e) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/e76e588e21f04e8ca9943b074be5b611) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/4c13649f996b42a68e53d73d899a0c00) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/1148bbb6dbd94440906e50d6e82f25ed) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/2e4f67db3c0347b9a5c7dd81c4d319c7) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/942258c989664f26b8d64fd5ef7e8f76) SUCCESS in 2m 29s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/367a7fa0d8784d61b3601ef12c9dc012) SUCCESS in 3m 09s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/1167e25cd7274584852a12e6f72b4020) SUCCESS in 3m 04s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by oshogbo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20)* status: 0 of 11 files reviewed, all discussions resolved

___
*[`graminescaffolding/client.py` line 59 at r5](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-NkKtgri6gfzqDz6JgJ3:-NkKtgri6gfzqDz6JgJ4:bmsjlg2) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c1507dcbaa333494e38925b7b5cdc0b2071fedb7/graminescaffolding/client.py#L59)):*
> ```Python
>     else:
>         os.environ[var] = value
> ```

New line - not blocking.
___
*[`graminescaffolding/client.py` line 70 at r5](https://reviewable.io/reviews/intel/ScaffoldingForGramine/20#-NkKtkXm2bY61RczRAWh:-NkKtkXn8DQGuXrChjbv:bs4q9p6) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/c1507dcbaa333494e38925b7b5cdc0b2071fedb7/graminescaffolding/client.py#L70)):*
> ```Python
>     func.restype = ctypes.c_int
>     ret.value = func(der, len(der))
> ```

Ditto?

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/3537a9bb069d470f94b150e164a121cf

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8924faf8688645cc964baa56a6196e12) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/005234f50cfc4ac2b203872dcd14bac8) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/f73c21577ea148148a02a93656433240) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/016f3cf2af1842b7b0d8f88f3175c60e) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/85768d6f32f34095b76adbc7ac068847) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/21595189e2be4be5bc3274a3ba41a141) SUCCESS in 2m 43s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/d6b1c747027d4d62a40bd364592b2667) SUCCESS in 2m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/30408256ac2d4922b6da73dc291e781d) SUCCESS in 3m 10s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/f966a49b45804fa7b12cde628df7a177) SUCCESS in 4m 33s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/b18d13664b464fd9a5343e3d885f6406) SUCCESS in 7m 29s

**Pull request merged**
