### PR TITLE
Fix printing help

### PR DESCRIPTION
**Pull request by oshogbo**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/33)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/dbe478a752694157aaffb7c2efd25aca

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/bb246b4b1f0d479b8c677df70d1c8cba) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f99c326418e44bc3a4ec7d42511c05d9) SUCCESS in 51s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/7d2c50705d0a43f88b2e18a1cb75a304) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/d4a1994157d44349867527cca522ff0f) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/16392eb004a44248bf0b0305b860a7ab) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/7a25d1565dcb48749f3da13338f7eab7) SUCCESS in 2m 36s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/a80b16f0d1e54a098beb58aafbc75fa9) SUCCESS in 2m 48s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e99203ea0b02492ebd097be6083ffe8a) SUCCESS in 2m 58s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/a6f9ed146e144c94b451e9c1858dac28) SUCCESS in 5m 20s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/63a534328f9342d2aa5cc539aa16bcf1) SUCCESS in 5m 12s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/26c7805f46744bce996b30d1e91a6bc2) SUCCESS in 4m 27s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/6c15208324dc4399a87b37509d76f171) SUCCESS in 6m 39s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/eedad743a25849668eb91e859a4f744a) SUCCESS in 5m 55s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/33)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @oshogbo)

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/e984080ae9884e24b151ed577f5fc16a

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ab426716916543b094c5c6a158ec1309) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/46d7be24c3434c4b9000d8ce6a718f0c) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/623b7df4e2b7469f939ae98b75c7f0ca) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/1913ed8b09514477ac00bab8b966fe39) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/b5b558eaa0074e1b8e0cf88d06dc5ebf) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/70761b28af774572aea8a33e152b51b5) SUCCESS in 2m 45s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/6c0ab8f2d47d4d859e0209ce44cde315) SUCCESS in 3m 01s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/afc0d8ca8b7845c1bdec940fa703bdc6) SUCCESS in 3m 04s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/b315fae6375b4d15a94004536da54ca2) SUCCESS in 5m 32s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/fc5f1352faf1454da95b4b5073d2c332) SUCCESS in 6m 46s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/22240a233a6348cb83a7f222dfdf2100) SUCCESS in 4m 25s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d0e7360425004fc8bf2693ffad4fc94a) SUCCESS in 7m 32s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/693714cb87f443a98376f3c51ba5a0a0) SUCCESS in 7m 44s

**Pull request merged**
