### PR TITLE
Release 0.1

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/21)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/ff3666910e5943998c1c82f30c675e43

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/b5512adb0852442692d9feacb53fe935) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6669a347ca414ce8bd3c1284225d4f25) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b6f90fd0494f4232b7da7cd1963862dd) SUCCESS in 38s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/df2fa71f423349428205c700b6c01070) **FAILURE** in 54s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/d8905484f7db4308aff4d0e7e2f81da9) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/74f4d02263f247cd96dd86644038f15d) SUCCESS in 2m 38s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f8a7008a20d448fa97d83c2c80131a42) SUCCESS in 3m 00s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/fe6e2d68b00042d899829241fda95a1c) SUCCESS in 3m 05s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/ae18d7fa98c24289a3ea469a9ac41423

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/140caf8a845647589c9cb1e4af690310) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/183dc16cb8404ddcac16666c48cf468c) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/67b0843702d44955a561ecab1af59f4f) SUCCESS in 39s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/d0b9a4f3eabb42cfa82ceb1f63cbca5a) **FAILURE** in 1m 01s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/f0f80ffafff045b6b8d8ce645ae35977) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/cc30a927d0434f11911ed51c348dd1e1) SUCCESS in 2m 44s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/ba96c9123104458eacfa124d719bca58) SUCCESS in 2m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/726b48465f9b489485775b8954cc902a) SUCCESS in 3m 11s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/cd460bfffb99472f9717922faec200fd

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/11593124c82443f2906e8e9d359d33d6) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/dfc97c4c8d074acfbf14576a2644992f) SUCCESS in 47s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/52c25a67c5b643238104b3614afc8d96) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/26208fdbb12346a1b69627347f1f8f89) SUCCESS in 1m 02s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/63144da6e45141cc91a1560f1e49f75f) SUCCESS in 42s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/dff9875a82284a0baa345f50090b4ff3) SUCCESS in 3m 08s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/03247fa675634bd0be0730ad5115097f) SUCCESS in 3m 09s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/ebb648cf091b45eeb4b5e0cf1b640e75) SUCCESS in 3m 15s

**Review by oshogbo — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/21)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @woju)

**Pull request merged**
