### PR TITLE
Add dotnet framework

### PR DESCRIPTION
**Pull request by woju**
This is #13 by @omeg rebased on top of recent refactor and development.

- - -
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/28)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/a127911010dd4c5aa90c4691170bdcb9

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ce38a54b9a0b4acb883bdd6d507839e4) SUCCESS in 38s
:x: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0d1feb28cc8a458f8ca26f44f8ad0997) **FAILURE** in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/92c45bc24ed24a01a62af676c7a47771) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/fe945f014e9d428f8adae1e5a5baebdd) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/026e74d862af4232bbc1a76b49bfcfee) SUCCESS in 37s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/b663a728408849d4abf777b62f16e330) **FAILURE** in 1m 01s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/c9d83e36f8a74aa2b6dcb42df5c623a6) **FAILURE** in 59s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/25326c5431d0453ba7d4dbfdbae3b9fd) **FAILURE** in 59s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/68f289b1cec34071964a9065c5fdfd5c) **FAILURE** in 59s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/33edd4be97fe4b78808747b2a1a2bf18) **FAILURE** in 58s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/b8df341034c94afe94130e28feefe86b

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/31a766b277c045fba7575269f59f9c5f) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/29ad9f6820f54776b35e00a53606e6df) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/7cdd71a22a7c44df96db00c4ee5907b0) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/6adc3a74e5a14168b361a3e2eb628628) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/600d1f44ce044b0086566e792e5b92c0) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/340205fe0b1d4faa8e0fe76cfae31f50) SUCCESS in 3m 21s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/77a15cd010754326aaa2a2f51e7e674e) SUCCESS in 3m 43s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/9531463799d942bbaa4dd3d919d495c6) SUCCESS in 4m 14s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/07b62a2c3ce64053bb52fd0435385e8b) SUCCESS in 6m 09s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/c798b24ff23f474fbc538fcc85aaca96) SUCCESS in 7m 46s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/00b662b36fef4a9fad9525eab32eb8e2

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/115237e54d3b40ce883bf4f584aa1e41) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/ba62c3b21581416885902366690a0793) SUCCESS in 48s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/00ec79c6274149959387324862833cc3) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0b75ba2a86dd4ffaaa7e13420e94a88d) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/c0b6672ec8814c35beae59cafb19d355) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/ad8a271095d14d868d870c993f339040) SUCCESS in 2m 46s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/fd28f86c268b498ab7e8712252b00db6) SUCCESS in 2m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/6c0d0d3e38b24654a7f81754ec0e1c43) SUCCESS in 3m 15s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/cf33544b18fc4733bb1aba1dfb3e0e55) SUCCESS in 4m 39s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/fc0c34e85a0c48ae952eb39578f5426c) SUCCESS in 7m 53s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/0189fa6924264d6f872d7abdba2cd824) **FAILURE** in 57s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/1e1a1d4bfeb545b9ac46682acdab7a32

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8be6eb7475ed47d9a94284c4bbac7aab) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/1c536c03db88489f85a5a540ca4e4668) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/8b4259065a9149dd9e6606f58fdd9c32) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/b178ab0146ea46c794044d83fd528e21) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/ffdc1353d06b46b9b2b9bbab48fdddbb) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/b8b51920eade4ed4811cc0a6a2f973f1) SUCCESS in 2m 55s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/b12e996519a941ffae25d7ae20f0960c) SUCCESS in 2m 56s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/98af0776e3434fe9b624c3b37150a17b) SUCCESS in 3m 11s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/26efc24e57c24cb795c8ebcb12e219da) SUCCESS in 6m 08s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/abee69dd11ff4f70984cf84d25982519) SUCCESS in 8m 05s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/ba4160a9db424aa6a992577298027a45) **FAILURE** in 1m 07s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/278b208766344dc89b6a0c9a6e8122af

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/90325b137b7f4fd29ad8fbadd30a7b03) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f4ed9cae68584983ba15c301ac81fec7) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/f0c4af9455c2463fb4e7bd1f7f533f84) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/4b5f4bf4b0c64bd19bd0ab9002442472) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/cb9a498480e443dcb25952c9d3fe616d) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6fc4bfcf9ac3436c813833f5c47713f9) SUCCESS in 2m 52s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/5199d069756b43bba9a9784a1be9a1c5) SUCCESS in 2m 56s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/2c1adc836185451c8e5f1a426e34f04a) SUCCESS in 3m 06s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/dc3da572dddf453c9923d35e7e9d695c) SUCCESS in 4m 47s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/9a4e04ceecaf4d7a8361c2e5853ffdb4) SUCCESS in 9m 34s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/ab805325282144abafc838c773df49a1) **FAILURE** in 2m 43s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/93e4e99a31a14c3cb4051ab618845825

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/c2b7674950864a63b5399de1f54b8bdc) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/15d3e99babd644e5a2f096fcc5158add) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/e136ab5e8d90489a8929fa17bb8bf0a9) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/28f5cc55b9234ef6823c574c56227722) SUCCESS in 1m 26s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e94b559dc3e94f6daa536e89d8c8e246) SUCCESS in 39s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/a4c826772b4843be91de4fda3a847164) **FAILURE** in 1m 47s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/7420bbecc63d434483f5c282813b2aa2) **FAILURE** in 2m 53s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/0dd717ef39a341d0a1a40a14e6628995) **FAILURE** in 1m 53s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/7b490dddcf7843dbb729614fda1c6f4c) **FAILURE** in 2m 58s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/b8cc2accf0124b698358ba6494bc4faf) **FAILURE** in 3m 56s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1620474e0d89458d902c9f06ca188e36) **FAILURE** in 2m 22s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/ddca711e1bef470b9ee94022245e15dc

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/c84faa1f427d4db3b07064bd0b70f191) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/19eeec6e21c24bb2bfd8d37f918a2de6) SUCCESS in 57s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/e09961cb833140e3997f091c2e275eb1) SUCCESS in 41s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/a7d28275d4c74a2a8cfad9700eb77dd3) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/76e3c14683dc4a598a6f4a9090c33167) SUCCESS in 39s
:x: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6538f4cda56342399c7e837e47ece557) **FAILURE** in 2m 53s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/8afd48cb5b4a43e8a9a4d6441133644d) **FAILURE** in 1m 55s
:x: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/9539e7cd013349a0b55881bffaa4aa80) **FAILURE** in 3m 19s
:x: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/4ee6499c45d847f1a25ba14854de190c) **FAILURE** in 1m 57s
:x: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/2d41314ab4a94010950e45206eabbbfc) **FAILURE** in 4m 09s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/08eac8cb12a641138fb5b5620eb1fd49) **FAILURE** in 3m 26s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/639f4d7044cf4f408cad4279806b6e09

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/4dce88b0611e4f4f853d31b0ca10f35a) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/6167b36427074ac7a760ff540c504e54) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/3fa1bbcadf6c4171a62e3941461066cb) SUCCESS in 38s
:x: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/3bff9aa72771448c952a0fa4f7204ea8) **FAILURE** in 1m 03s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/34549140951b477b8c74f5c0c77e039a) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6916dac5105c48568e1653f8bcd487a9) SUCCESS in 2m 36s
:x: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/016f146005454c0f8f7b74ce2ea817f6) **FAILURE** in 2m 42s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/2b43be03f9194a6fa1d103c89e974ad8) SUCCESS in 3m 06s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/c0378ad5ea3e4df28ddd6a37c8654b20) SUCCESS in 4m 26s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/aaefe762a66f49928ba1b03684bdc849) SUCCESS in 8m 05s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/82acf4d481034c9eb697f0f79d93fc6f) **FAILURE** in 5m 14s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/3a67f001bd514e5e87b2619b9dd7eaad

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/8395945093fa4ac4bbe04152fb0045f9) SUCCESS in 39s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/21fa5cf4f2a0404aa39f6ef1ccf590b3) SUCCESS in 50s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/4f452f9a1d5c4581bf4f827ce9306303) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/4a78f34fb6fc42a1b29cf87ad278543f) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/5fc3f2aa754f4b8ca164851fa68a9592) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/af3e841fe7284cabb46d1af50bcbf6a2) SUCCESS in 2m 42s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/1aae7ca4fdc44163aaa46fec90c6b55a) SUCCESS in 2m 59s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/b4f9310d560c4454858efe46b66ee6bc) SUCCESS in 3m 04s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/d311208d52764a4eb22263981842f0fd) SUCCESS in 4m 24s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/7eed4a5930a34fd8b9380306a3bf9baa) SUCCESS in 8m 11s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/2ff30e1a9a444538a66c8e36b7faa1c5) **FAILURE** in 4m 32s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/4967d366af9744398e64be2cebdc9425

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/ed35a9c380f4426ca0894c30ea277724) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/f42a2668b34c4ca3911641ea3f5ddabd) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/ad0241c813cc4b809ca3842723657cdb) SUCCESS in 40s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/34495bed276244ce96192bcae5eb7314) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/e5679eefaa694b1e94cead3a770fd978) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/871e23e780a549f38b29d0c8af65ac33) SUCCESS in 2m 42s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/22b30cd4624f42ed8255f8f1fb0afa6a) SUCCESS in 3m 20s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/e3b41733822e410a9023698afadb2163) SUCCESS in 3m 06s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/7cdc7325e441485d83c0bc0b0a9d98d2) SUCCESS in 4m 21s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/d478e0ddfee446bc9b100da8f07e3099) SUCCESS in 9m 53s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/71e8e317bb8e4a7a9c819f246284e74f) **FAILURE** in 5m 15s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/2f0d79b5215740548578141af62f8a4d

:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/f7a38cb25dac4489b514912b43bfcfbf) SUCCESS in 7m 45s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/9afa3716927742438db3f3e28064a000

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/34e80c6110e94c00a58af3ab38cd3f67) SUCCESS in 37s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/9dbe43e44bd64bfe88ca5304dbb01399) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/1e19c15581e848a686ee722da95d42ac) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/5474c078d06b40d28b74128072e6b3e1) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/7923902e7c7b4830af0414b64b0f95c1) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/16fbb1304ad148388b83908db5aaa025) SUCCESS in 2m 45s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/1a75789fc5c24c77ab92c2fd8e9fc826) SUCCESS in 3m 11s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/85c1ada6353045869e841e7c78244008) SUCCESS in 2m 58s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/518d8d492ca24db7a0d43cf20898bc45) SUCCESS in 4m 40s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/ce9f0be6bc81425fa200e6f43f2fbfa5) SUCCESS in 7m 40s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/a68f74be3fe44955ad530aa1b006cf62) SUCCESS in 8m 12s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/340df56967814a47a3007c862e64889d

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/7685eafa419247e89dba664063c3956a) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/5be27f3bbbfe48f7945ecf6c2e7763a7) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/b8071f09ebb14d1e902eddbd351ce402) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/7b455d8f38484d98b0c144622166b565) SUCCESS in 1m 06s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/069012879aa341478c7d0a508cdc3990) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/cb20b850f451486089bbacaf2ea227e9) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/b7c2101d50014910902ddfefb2bb212e) SUCCESS in 3m 00s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/feaaa1764f754b7086c4a6e08de28b6e) SUCCESS in 2m 58s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/4050b425472846d89bf270b83e315217) SUCCESS in 5m 43s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/e51dffc757a740e983f1fbd8de888faf) SUCCESS in 8m 18s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1105ae8c809f49228f78127f2dd8587a) SUCCESS in 6m 51s

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build failed.
https://zuul.gramineproject.io/t/scaffolding/buildset/7103ee8870a442a3b73d25b547dc0da4

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/27822a4628a74e829c2f0ddbf53107de) SUCCESS in 40s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/0b2ccd230eab49968f720667e8be917c) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/d3bedd65393a4362a0fd4b671e13d065) SUCCESS in 39s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/796295fa2d61419cb8da350112301e18) SUCCESS in 1m 05s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/c5bd8ea715ba436884ea0c177c72907c) SUCCESS in 38s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/1e1f3cfc1686456b91d6c6f6d7ae3bfa) SUCCESS in 2m 48s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/090930dd3dc24972b69added3adbce1e) SUCCESS in 4m 35s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/3f1119593d2849fda2063b9f45c4fbb6) SUCCESS in 4m 03s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/f0b2c4c0c51844e1895c51cab6f2ccf9) SUCCESS in 4m 36s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/c6ff9c260f3f43bea85ae90a4962e576) SUCCESS in 9m 44s
:x: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/1e20922a1a4142f99be210f1662c3a3c) **FAILURE** in 6m 02s

**Review by oshogbo — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/28#-:-NlNnYdc7MvdovApDLXI:bnfp4nl)* status: 0 of 25 files reviewed, all discussions resolved

**Pull request merged**
