### PR TITLE
Documentation for customisation

### PR DESCRIPTION
**Pull request by woju**
This change is [Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38)

### CODE REVIEW

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/95d69884b80a4dc9a89d21d41198ee49

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/d79885bc86ec43a881cabaa819334439) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/40709498b4054852bfa664907177d4c5) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/82db8b88a0c64144bb618ddd0fb78e75) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/0f22a38a9ca94da2b5fdad1312812a54) SUCCESS in 1m 04s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/d8db7b255b444a1fa9d01be646e016ed) SUCCESS in 37s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/6092ffcc10d14e22802f82580311fae5) SUCCESS in 3m 06s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/9bf6248b0a534fbfb7cda1313a2b66cc) SUCCESS in 4m 12s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/b5989d4575324b1680f478f1cc1e5e92) SUCCESS in 5m 01s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/51328863977f400c8b5c1000395317a6) SUCCESS in 6m 40s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/4c195d4e3be64e939526dec9f7d43aa7) SUCCESS in 8m 37s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/790633c472bd4721b29c6d9276a60b3e) SUCCESS in 8m 35s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/0093458e374248e09ca5ed86c5dc1dad) SUCCESS in 13m 22s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/642daf585b444c1da977180170280b77) SUCCESS in 10m 36s

**Review by oshogbo — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @woju)

___
*[`Documentation/templates.rst` line 10 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBpYYE1STdNB_hKrM8:-NoBpYYE1STdNB_hKrM9:b-3765xm) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L10)):*
> ```reStructuredText
> resulting directory (containing both user's application and mentioned
> renderings) into system image, measuring and signing it, and last but not least,
> packaging everything into docker (OCI) container.
> ```

I believe the official name is with a capital letter.



_Suggestion:_
```reStructuredText
Docker
```
___
*[`Documentation/templates.rst` line 12 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBolUL15sqxpEhWW7W:-NoBolUL15sqxpEhWW7X:bhlzj6x) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L12)):*
> ```reStructuredText
> packaging everything into docker (OCI) container.
> 
> If you need to customise some of those files, it might be that you need to
> ```

I believe Gramine uses American English.



_Suggestion:_
```reStructuredText
customize
```
___
*[`Documentation/templates.rst` line 28 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBp0Dr77ucwOdlRaSH:-NoBp0Dr77ucwOdlRaSI:b45h) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L28)):*
> ```reStructuredText
> template name.
> 
> SCAG uses `Jinja <https://jinja.palletsprojects.com/>`__ templates. Introducion
> ```





_Suggestion:_
```reStructuredText
Introduction
```
___
*[`Documentation/templates.rst` line 81 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBpFyx1xmLNbmDnvtI:-NoBpFyx1xmLNbmDnvtJ:b45h) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L81)):*
> ```reStructuredText
> - File ``.scag/Dockerfile-final`` is responsible for replacing
>   ``app.manifest.sgx`` and ``app.sig`` (SIGSTRUCT) inside the container.
>   Rendered from ``Dockerfile-final``. It is not advisable to overrider this
> ```





_Suggestion:_
```reStructuredText
override
```

**Comment by gramine-scaffolding** [comment]
Starting check jobs.

**Review by woju — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @oshogbo)

___
*[`Documentation/templates.rst` line 10 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBpYYE1STdNB_hKrM8:-NoBq0Zn8UqA72Y_aB_O:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L10)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I believe the official name is with a capital letter.
</blockquote></details>

Done.
___
*[`Documentation/templates.rst` line 12 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBolUL15sqxpEhWW7W:-NoBq_6q9Q-0ufdFQam-:b-57ct29) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L12)):*
<details><summary><i>Previously, oshogbo (Mariusz Zaborski) wrote…</i></summary><blockquote>

I believe Gramine uses American English.
</blockquote></details>

I've removed whole paragraph, it's redundant.
___
*[`Documentation/templates.rst` line 28 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBp0Dr77ucwOdlRaSH:-NoBrGKQC004TOK0Ws-L:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L28)):*
> ```reStructuredText
> template name.
> 
> SCAG uses `Jinja <https://jinja.palletsprojects.com/>`__ templates. Introducion
> ```

Done.
___
*[`Documentation/templates.rst` line 81 at r1](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38#-NoBpFyx1xmLNbmDnvtI:-NoBrDk1EIUBWsf4vo_y:b-896fix) ([raw file](https://github.com/intel/ScaffoldingForGramine/blob/e1080e9e18fd81d7ad28ed90c0b424d17ee97070/Documentation/templates.rst#L81)):*
> ```reStructuredText
> - File ``.scag/Dockerfile-final`` is responsible for replacing
>   ``app.manifest.sgx`` and ``app.sig`` (SIGSTRUCT) inside the container.
>   Rendered from ``Dockerfile-final``. It is not advisable to overrider this
> ```

Done.

**Comment by gramine-scaffolding** [comment]
Build succeeded.
https://zuul.gramineproject.io/t/scaffolding/buildset/cedc25f84b56422abe3daaba3f68c5dc

:heavy_check_mark: [bandit ](https://zuul.gramineproject.io/t/scaffolding/build/309a40cfb0804f2ca15c4da053eb08a2) SUCCESS in 38s
:heavy_check_mark: [pylint ](https://zuul.gramineproject.io/t/scaffolding/build/2d43401ab2224fd7a9f73e8704a601dc) SUCCESS in 49s
:heavy_check_mark: [pytest ](https://zuul.gramineproject.io/t/scaffolding/build/25b2b792f5a34a1da9772d5006fb88ca) SUCCESS in 38s
:heavy_check_mark: [build-deb ](https://zuul.gramineproject.io/t/scaffolding/build/05aaaf782c3047d5bd7355b11b66f09d) SUCCESS in 1m 07s
:heavy_check_mark: [build-docs ](https://zuul.gramineproject.io/t/scaffolding/build/7eaca87dbee74082a2ff7b986c1c19ad) SUCCESS in 39s
:heavy_check_mark: [test-python ](https://zuul.gramineproject.io/t/scaffolding/build/c32642a87cea45498118a156966f1b54) SUCCESS in 2m 55s
:heavy_check_mark: [test-flask ](https://zuul.gramineproject.io/t/scaffolding/build/f7e14847c8b14d71bd3622b98aa2580d) SUCCESS in 3m 04s
:heavy_check_mark: [test-nodejs ](https://zuul.gramineproject.io/t/scaffolding/build/349f1d6a62584fbfb48f60944efbed44) SUCCESS in 3m 14s
:heavy_check_mark: [test-expressjs ](https://zuul.gramineproject.io/t/scaffolding/build/b394c8a0b37a474fa8fce532b861464b) SUCCESS in 5m 47s
:heavy_check_mark: [test-koajs ](https://zuul.gramineproject.io/t/scaffolding/build/dc5645056b0b446e8f630138e062904c) SUCCESS in 5m 59s
:heavy_check_mark: [test-java-jar ](https://zuul.gramineproject.io/t/scaffolding/build/a305f7c02949415c8965d819f3cb5182) SUCCESS in 4m 37s
:heavy_check_mark: [test-java-gradle ](https://zuul.gramineproject.io/t/scaffolding/build/198dba900ef44e958a35f96651fe7d4b) SUCCESS in 8m 40s
:heavy_check_mark: [test-dotnet ](https://zuul.gramineproject.io/t/scaffolding/build/70c637a5bc184be98ec8687fc71bb370) SUCCESS in 8m 10s

**Review by oshogbo — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/intel/ScaffoldingForGramine/38)* status: 0 of 2 files reviewed, all discussions resolved

**Pull request merged**
